# -*- coding: utf-8 -*-

"""
    zjecfsdagl

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from zjecfsdagl.decorators import lazy_property
from zjecfsdagl.configuration import Configuration
from zjecfsdagl.controllers.api_controller import APIController


class ZjecfsdaglClient(object):

    config = Configuration

    @lazy_property
    def client(self):
        return APIController()


    def __init__(self,
                 basic_auth_user_name=None,
                 basic_auth_password=None):
        if basic_auth_user_name != None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password != None:
            Configuration.basic_auth_password = basic_auth_password


