# Generated by Django 2.0.6 on 2018-08-18 07:15
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='digital_assets/attachments')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('attachment_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='digital_assets/audio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('audio_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='digital_assets/pictures')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DigitalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='digital_assets/video')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('video_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
