# Generated by Django 2.0.6 on 2018-08-18 07:15
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ACCOUNT_USER_PROXY_MODEL),
        ('digital_assets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCOUNT_USER_PROXY_MODEL),
        ),
        migrations.AddField(
            model_name='digitalimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCOUNT_USER_PROXY_MODEL),
        ),
        migrations.AddField(
            model_name='digitalaudio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCOUNT_USER_PROXY_MODEL),
        ),
        migrations.AddField(
            model_name='digitalattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCOUNT_USER_PROXY_MODEL),
        ),
    ]
