
- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest
    gate:
      queue: monasca
      jobs:
        - monasca-tempest-python-influxdb
        - monasca-tempest-python-cassandra
        - monascalog-tempest
