
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-02T02:33:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "97c47560c58f4192a689072b65b394691b48be54",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
