# Version file autogenerated by the build process
version = '0.6.0'
build = '251'
vcs_info = 'Git SHA1 78c1ae04 committed on 2019-02-06'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.6.0"\nKSCONF_BUILD="251"\nKSCONF_VCS_INFO="Git SHA1 78c1ae04 committed on 2019-02-06"')
