[tool.poetry]
name = "rcache"
version = "1.0.0"
description = "Redis memoize cache"
authors = ["Michal Klich <michal@michalklich.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/the_speedball/redis.cache.py"

[tool.poetry.dependencies]
python = "^3.6"
redis = "^3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
