# Generated by Django 2.1.5 on 2019-02-08 07:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deeppages', '0003_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, help_text='Unique identifier to be used on imports and other references', populate_from='name', unique_with=('pk',)),
        ),
    ]
