sudo: required
language: python

env:
  - IMAGE_NAME=python2-stable
  - IMAGE_NAME=python3-stable

services:
  - docker

install:
  - pip install mako

script:
  - docker version
  - cd docker
  - make build image=$IMAGE_NAME

after_success:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - make push image=$IMAGE_NAME
