[tool.poetry]
name = "dry-monads"
version = "0.1.0"
description = "Monads for python made simple and safe."
authors = ["sobolevn <mail@sobolevn.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
typing-extensions = "^3.7"

[tool.poetry.dev-dependencies]
mypy = "^0.660.0"
wemake-python-styleguide = "^0.7.0"
flake8-pytest = "^1.3"
safety = "^1.8"
pytest = "^4.1"
pytest-cov = "^2.6"
pytest-randomly = "^1.2"
sphinx = "^1.8"
sphinx-autodoc-typehints = "^1.6"
sphinxcontrib-mermaid = "^0.3.1"
doc8 = "^0.8.0"
m2r = "^0.2.1"
tomlkit = "^0.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
