[tool.poetry]
name = "red-connector-ssh"
version = "0.5"
authors = ["Christoph Jansen <Christoph.Jansen@htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-ssh"
homepage = "https://curious-containers.github.io/"
description = "RED Connector SSH is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
jsonschema = "^2.6"
paramiko = "^2.4"
scp = "^0.13.0"
cc-connector-cli = "^0.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-ssh = 'red_connector_ssh.main:main'
red-convert-ssh-key = 'red_connector_ssh.convert_key:main'
