---
########################################################################
# pypiserver docker-compose example
########################################################################

version: "3.3"

services:
    pypiserver:
        image: pypiserver/pypiserver:latest
        volumes:
            - type: bind
              source: ./data
              target: /data
        # Use an .htpasswd file to control access, serve packages from
        # ./data (which will be /data in the container)
        command: -P /data/.htpasswd -a update,download,list /data/packages
        ports:
            - "80:8080"
volumes:
    data:
