[tool.poetry]
name = "xini"
version = "0.2.2"
description = ""
license = "BSD-3-Clause"
authors = ["Mark Gemmill <mark@markgemmill.com>"]
readme = "README.md"
homepage = "https://bitbucket.org/mgemmill/xini/src/master/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.6",
]
include = ["LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"
docopt = "^0.6.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.6"
flake8 = "^3.6"
pylint = "^2.2"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.poetry.scripts]
xini = 'xini:main'

[tool.black]
py36 = true
verbose = true

[tool.pytest]
addopts = "-vv --strict --cov=xini --cov-report=term-missing"

[tool.coverage.run]
source = "xini"
branch = true

[tool.coverage.paths]
source = "src/xini"

[tool.coverage.report]
show_missing = true

[tool.flake8]
enable-extensions="G"
ignore = ["E501"]
exclude = [".git","__pycache__","build","dist","x_api.py"]
show-source = true
max-complexity = 10

[tool.pylint]
disable = ["missing-docstring", 
    "R1710",
    "invalid-name"]

[tool.dover]
versioned_files = ["pyproject.toml", "src/xini/__init__.py"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
