[tool.poetry]
name = "cachedprop"
version = "0.1.0"
description = "cached property method decorator"
authors = ["Joao Valverde <acci.valverde@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
flake8 = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
