# Generated by Django 2.0 on 2018-12-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('street', models.CharField(default='', max_length=300)),
                ('address', models.CharField(default='', max_length=300)),
                ('post_code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(default=None, max_length=50, verbose_name='地区编号')),
                ('area', models.CharField(default=None, max_length=60, verbose_name='区')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(default=None, max_length=6, verbose_name='城市编号')),
                ('city', models.CharField(default=None, max_length=50, verbose_name='市/县')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(default=None, max_length=6, verbose_name='省份编号')),
                ('province', models.CharField(default=None, max_length=40, verbose_name='省份')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='father',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='location.Province', verbose_name='所属省份'),
        ),
        migrations.AddField(
            model_name='area',
            name='father',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='location.City', verbose_name='所属城市'),
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.Area'),
        ),
    ]
