
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ba12ed7672bd8bb558ba2509c6fe9121c3e8a3a0",
 "version": "7.5.0beta1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
