# Generated by Django 2.0.6 on 2018-08-18 07:15

import django.db.models.deletion
from django.db import migrations, models

import ccc.ocr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/ocr/images')),
                ('phones', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('emails', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('converted_text', models.TextField(blank=True, default=None, null=True)),
                ('unique_upload_id', models.CharField(default=ccc.ocr.models.generateUUID, max_length=100)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.Campaign')),
            ],
        ),
    ]
