# Generated by Django 2.0.6 on 2018-08-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontacts',
            name='survey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Survey'),
        ),
    ]
