stages:
  - test
  - deploy


python2.7:
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-2.7
  script:
    - python setup.py bdist_wheel --dist-dir public/LbSoftConfDb2Clients
    - python setup.py sdist --dist-dir public/LbSoftConfDb2Clients
  artifacts:
    paths:
      - cover_report
      - pep8_report
      - public
    when: always
    expire_in: 1 week
  tags:
    - cvmfs


# see https://gitlab.cern.ch/gitlabci-examples/deploy_eos for the details
# of the configuration
deploy-packages:
  stage: deploy
  only:
    - tags
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - test -z "$EOS_ACCOUNT_USERNAME" -o -z "$EOS_ACCOUNT_PASSWORD" -o -z "$EOS_PATH" && exit 0 || true
    # Script that performs the deploy to EOS. Makes use of the variables defined in the project
    # It will copy the generated content to the folder in EOS
    - deploy-eos
  # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []
