binary_sensor:
  - platform: ping
    host: powiedz.co
    count: 2
    scan_interval: 30

sensor:
  - platform: mqtt
    state_topic: ais/version/sensor
    name: version_info

group:
  dom_system_version:
    control: hidden
    entities:
      - sensor.version_info
      - weblink.upgrade_log
      - script.ais_restart_system
      - script.ais_stop_system
  #  dom_cloud:
  #    control: hidden
  #    entities:
  #      - binary_sensor.ping_binary_sensor
  #      - weblink.cloud
  #      - weblink.upgrade_log
