# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
language: python
sudo: required
addons:
  postgresql: 9.6
matrix:
  include:
    - name: Python 3.6, PG 9.6
      python: 3.6
      env: DATABASE=postgres
    - name: Python 3.7, PG 9.6
      python: 3.7
      env: DATABASE=postgres

services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database guillotina;' -U postgres

cache:
  directories:
    - eggs
install:
  - pip install Cython==0.27.3
  - pip install -r requirements.txt
  - pip install -e .[test]
  - pip install flake8
  - sleep 5
script:
  - flake8 guillotina_dynamictablestorage --config=setup.cfg
  - pytest -s --cov=guillotina_dynamictablestorage -s --tb=native -v --cov-report term-missing --cov-append guillotina_dynamictablestorage