# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_resources/AddConditionDialog.ui',
# licensing of 'qt_resources/AddConditionDialog.ui' applies.
#
# Created: Thu Dec 27 16:24:07 2018
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddConditionDialog(object):
    def setupUi(self, AddConditionDialog):
        AddConditionDialog.setObjectName("AddConditionDialog")
        AddConditionDialog.resize(614, 511)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddConditionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.condDetails = QtWidgets.QGroupBox(AddConditionDialog)
        self.condDetails.setObjectName("condDetails")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.condDetails)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.location = QtWidgets.QGroupBox(self.condDetails)
        self.location.setObjectName("location")
        self.formLayout = QtWidgets.QFormLayout(self.location)
        self.formLayout.setObjectName("formLayout")
        self.folderLabel = QtWidgets.QLabel(self.location)
        self.folderLabel.setObjectName("folderLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.folderLabel)
        self.folder = QtWidgets.QComboBox(self.location)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder.sizePolicy().hasHeightForWidth())
        self.folder.setSizePolicy(sizePolicy)
        self.folder.setObjectName("folder")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.folder)
        self.channel = QtWidgets.QLineEdit(self.location)
        self.channel.setObjectName("channel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.channel)
        self.channelLabel = QtWidgets.QLabel(self.location)
        self.channelLabel.setObjectName("channelLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.channelLabel)
        self.since = TimePointEdit(self.location)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.since.sizePolicy().hasHeightForWidth())
        self.since.setSizePolicy(sizePolicy)
        self.since.setObjectName("since")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.since)
        self.until = TimePointEdit(self.location)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.until.sizePolicy().hasHeightForWidth())
        self.until.setSizePolicy(sizePolicy)
        self.until.setObjectName("until")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.until)
        self.sinceLabel = QtWidgets.QLabel(self.location)
        self.sinceLabel.setObjectName("sinceLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sinceLabel)
        self.untilLabel = QtWidgets.QLabel(self.location)
        self.untilLabel.setObjectName("untilLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.untilLabel)
        self.horizontalLayout.addWidget(self.location)
        self.payloadKeys = QtWidgets.QGroupBox(self.condDetails)
        self.payloadKeys.setObjectName("payloadKeys")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.payloadKeys)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fields = QtWidgets.QListView(self.payloadKeys)
        self.fields.setObjectName("fields")
        self.verticalLayout_2.addWidget(self.fields)
        self.editKey = QtWidgets.QPushButton(self.payloadKeys)
        self.editKey.setObjectName("editKey")
        self.verticalLayout_2.addWidget(self.editKey)
        self.horizontalLayout.addWidget(self.payloadKeys)
        self.verticalLayout.addWidget(self.condDetails)
        self.stack = QtWidgets.QGroupBox(AddConditionDialog)
        self.stack.setObjectName("stack")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.stack)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.stack)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.utc = QtWidgets.QCheckBox(self.widget_3)
        self.utc.setObjectName("utc")
        self.horizontalLayout_2.addWidget(self.utc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addButton = QtWidgets.QToolButton(self.widget_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        self.removeButton = QtWidgets.QToolButton(self.widget_3)
        self.removeButton.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon1)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_2.addWidget(self.removeButton)
        self.upButton = QtWidgets.QToolButton(self.widget_3)
        self.upButton.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon2)
        self.upButton.setObjectName("upButton")
        self.horizontalLayout_2.addWidget(self.upButton)
        self.downButton = QtWidgets.QToolButton(self.widget_3)
        self.downButton.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon3)
        self.downButton.setObjectName("downButton")
        self.horizontalLayout_2.addWidget(self.downButton)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.conditionsStackView = QtWidgets.QTableView(self.stack)
        self.conditionsStackView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.conditionsStackView.setObjectName("conditionsStackView")
        self.verticalLayout_3.addWidget(self.conditionsStackView)
        self.verticalLayout.addWidget(self.stack)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddConditionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddConditionDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AddConditionDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AddConditionDialog.reject)
        QtCore.QObject.connect(self.since, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), self.until.setMinimumDateTime)
        QtCore.QObject.connect(self.until, QtCore.SIGNAL("dateTimeChanged(QDateTime)"), self.since.setMaximumDateTime)
        QtCore.QObject.connect(self.until, QtCore.SIGNAL("maxChecked()"), self.since.resetMaximumDateTime)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("helpRequested()"), AddConditionDialog.showHelp)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL("clicked()"), AddConditionDialog.addCondition)
        QtCore.QObject.connect(self.removeButton, QtCore.SIGNAL("clicked()"), AddConditionDialog.removeCondition)
        QtCore.QObject.connect(self.upButton, QtCore.SIGNAL("clicked()"), AddConditionDialog.moveUp)
        QtCore.QObject.connect(self.downButton, QtCore.SIGNAL("clicked()"), AddConditionDialog.moveDown)
        QtCore.QObject.connect(self.editKey, QtCore.SIGNAL("clicked()"), AddConditionDialog.editCondition)
        QtCore.QMetaObject.connectSlotsByName(AddConditionDialog)

    def retranslateUi(self, AddConditionDialog):
        AddConditionDialog.setWindowTitle(QtWidgets.QApplication.translate("AddConditionDialog", "Add Condition", None, -1))
        self.condDetails.setTitle(QtWidgets.QApplication.translate("AddConditionDialog", "Condition Object Details", None, -1))
        self.location.setTitle(QtWidgets.QApplication.translate("AddConditionDialog", "Location", None, -1))
        self.folderLabel.setText(QtWidgets.QApplication.translate("AddConditionDialog", "Folder", None, -1))
        self.channelLabel.setText(QtWidgets.QApplication.translate("AddConditionDialog", "Channel", None, -1))
        self.sinceLabel.setText(QtWidgets.QApplication.translate("AddConditionDialog", "Since", None, -1))
        self.untilLabel.setText(QtWidgets.QApplication.translate("AddConditionDialog", "Until", None, -1))
        self.payloadKeys.setTitle(QtWidgets.QApplication.translate("AddConditionDialog", "Payload Keys", None, -1))
        self.editKey.setToolTip(QtWidgets.QApplication.translate("AddConditionDialog", "Edit the selected field", None, -1))
        self.editKey.setText(QtWidgets.QApplication.translate("AddConditionDialog", "Edit", None, -1))
        self.stack.setTitle(QtWidgets.QApplication.translate("AddConditionDialog", "Condition Objects Stack", None, -1))
        self.utc.setText(QtWidgets.QApplication.translate("AddConditionDialog", "UTC", None, -1))
        self.addButton.setToolTip(QtWidgets.QApplication.translate("AddConditionDialog", "Add condition to the stack", None, -1))
        self.addButton.setText(QtWidgets.QApplication.translate("AddConditionDialog", "add", None, -1))
        self.removeButton.setToolTip(QtWidgets.QApplication.translate("AddConditionDialog", "Remove condition from the stack", None, -1))
        self.removeButton.setText(QtWidgets.QApplication.translate("AddConditionDialog", "remove", None, -1))
        self.upButton.setToolTip(QtWidgets.QApplication.translate("AddConditionDialog", "Move condition up", None, -1))
        self.upButton.setText(QtWidgets.QApplication.translate("AddConditionDialog", "up", None, -1))
        self.downButton.setToolTip(QtWidgets.QApplication.translate("AddConditionDialog", "Move condition down", None, -1))
        self.downButton.setText(QtWidgets.QApplication.translate("AddConditionDialog", "down", None, -1))

from CondDBBrowser.CondDBUI.Browser.Widgets import TimePointEdit
import Resources_rc
