# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_resources/NewNodeDialog.ui',
# licensing of 'qt_resources/NewNodeDialog.ui' applies.
#
# Created: Thu Dec 27 16:24:07 2018
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_NewNodeDialog(object):
    def setupUi(self, NewNodeDialog):
        NewNodeDialog.setObjectName("NewNodeDialog")
        NewNodeDialog.resize(498, 452)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewNodeDialog.sizePolicy().hasHeightForWidth())
        NewNodeDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(NewNodeDialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.basicInfosWidget = QtWidgets.QWidget(NewNodeDialog)
        self.basicInfosWidget.setObjectName("basicInfosWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.basicInfosWidget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nodeNameLabel = QtWidgets.QLabel(self.basicInfosWidget)
        self.nodeNameLabel.setObjectName("nodeNameLabel")
        self.verticalLayout_3.addWidget(self.nodeNameLabel)
        self.nodeNameComboBox = QtWidgets.QComboBox(self.basicInfosWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nodeNameComboBox.sizePolicy().hasHeightForWidth())
        self.nodeNameComboBox.setSizePolicy(sizePolicy)
        self.nodeNameComboBox.setEditable(True)
        self.nodeNameComboBox.setObjectName("nodeNameComboBox")
        self.verticalLayout_3.addWidget(self.nodeNameComboBox)
        self.descriptionLabel = QtWidgets.QLabel(self.basicInfosWidget)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_3.addWidget(self.descriptionLabel)
        self.descriptionEdit = QtWidgets.QLineEdit(self.basicInfosWidget)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_3.addWidget(self.descriptionEdit)
        self.basicInfosWidget2 = QtWidgets.QWidget(self.basicInfosWidget)
        self.basicInfosWidget2.setObjectName("basicInfosWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.basicInfosWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nodeTypeGB = QtWidgets.QGroupBox(self.basicInfosWidget2)
        self.nodeTypeGB.setObjectName("nodeTypeGB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.nodeTypeGB)
        self.verticalLayout.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.multiVersBtn = QtWidgets.QRadioButton(self.nodeTypeGB)
        self.multiVersBtn.setChecked(True)
        self.multiVersBtn.setObjectName("multiVersBtn")
        self.verticalLayout.addWidget(self.multiVersBtn)
        self.singleVersBtn = QtWidgets.QRadioButton(self.nodeTypeGB)
        self.singleVersBtn.setObjectName("singleVersBtn")
        self.verticalLayout.addWidget(self.singleVersBtn)
        self.foldersetBtn = QtWidgets.QRadioButton(self.nodeTypeGB)
        self.foldersetBtn.setObjectName("foldersetBtn")
        self.verticalLayout.addWidget(self.foldersetBtn)
        self.horizontalLayout.addWidget(self.nodeTypeGB)
        self.basicInfosWidget3 = QtWidgets.QWidget(self.basicInfosWidget2)
        self.basicInfosWidget3.setObjectName("basicInfosWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.basicInfosWidget3)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.createParentsCheckBox = QtWidgets.QCheckBox(self.basicInfosWidget3)
        self.createParentsCheckBox.setObjectName("createParentsCheckBox")
        self.verticalLayout_2.addWidget(self.createParentsCheckBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.editFieldsBtn = QtWidgets.QPushButton(self.basicInfosWidget3)
        self.editFieldsBtn.setCheckable(True)
        self.editFieldsBtn.setObjectName("editFieldsBtn")
        self.verticalLayout_2.addWidget(self.editFieldsBtn)
        self.horizontalLayout.addWidget(self.basicInfosWidget3)
        self.verticalLayout_3.addWidget(self.basicInfosWidget2)
        self.gridLayout.addWidget(self.basicInfosWidget, 0, 0, 4, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewNodeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.fieldsGB = QtWidgets.QGroupBox(NewNodeDialog)
        self.fieldsGB.setObjectName("fieldsGB")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fieldsGB)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fieldsView = QtWidgets.QTableView(self.fieldsGB)
        self.fieldsView.setAlternatingRowColors(True)
        self.fieldsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.fieldsView.setObjectName("fieldsView")
        self.verticalLayout_4.addWidget(self.fieldsView)
        self.widget = QtWidgets.QWidget(self.fieldsGB)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.removeFieldBtn = QtWidgets.QToolButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeFieldBtn.setIcon(icon)
        self.removeFieldBtn.setObjectName("removeFieldBtn")
        self.horizontalLayout_2.addWidget(self.removeFieldBtn)
        self.addFieldBtn = QtWidgets.QToolButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFieldBtn.setIcon(icon1)
        self.addFieldBtn.setObjectName("addFieldBtn")
        self.horizontalLayout_2.addWidget(self.addFieldBtn)
        self.verticalLayout_4.addWidget(self.widget)
        self.gridLayout.addWidget(self.fieldsGB, 4, 0, 1, 1)
        self.nodeNameLabel.setBuddy(self.nodeNameComboBox)
        self.descriptionLabel.setBuddy(self.descriptionEdit)

        self.retranslateUi(NewNodeDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NewNodeDialog.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NewNodeDialog.accept)
        QtCore.QObject.connect(self.foldersetBtn, QtCore.SIGNAL("toggled(bool)"), NewNodeDialog.foldersetButtonToggled)
        QtCore.QObject.connect(self.editFieldsBtn, QtCore.SIGNAL("toggled(bool)"), self.fieldsGB.setVisible)
        QtCore.QObject.connect(self.nodeNameComboBox, QtCore.SIGNAL("textChanged(QString)"), NewNodeDialog.checkValid)
        QtCore.QObject.connect(self.createParentsCheckBox, QtCore.SIGNAL("stateChanged(int)"), NewNodeDialog.checkValid)
        QtCore.QObject.connect(self.addFieldBtn, QtCore.SIGNAL("clicked()"), NewNodeDialog.addField)
        QtCore.QObject.connect(self.removeFieldBtn, QtCore.SIGNAL("clicked()"), NewNodeDialog.removeField)
        QtCore.QMetaObject.connectSlotsByName(NewNodeDialog)

    def retranslateUi(self, NewNodeDialog):
        NewNodeDialog.setWindowTitle(QtWidgets.QApplication.translate("NewNodeDialog", "New Node", None, -1))
        self.nodeNameLabel.setText(QtWidgets.QApplication.translate("NewNodeDialog", "Node &name", None, -1))
        self.descriptionLabel.setText(QtWidgets.QApplication.translate("NewNodeDialog", "&Description", None, -1))
        self.nodeTypeGB.setTitle(QtWidgets.QApplication.translate("NewNodeDialog", "Type", None, -1))
        self.multiVersBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "M&ulti version", None, -1))
        self.singleVersBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "S&ingle version", None, -1))
        self.foldersetBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "&FolderSet", None, -1))
        self.createParentsCheckBox.setText(QtWidgets.QApplication.translate("NewNodeDialog", "Create &parents", None, -1))
        self.editFieldsBtn.setStatusTip(QtWidgets.QApplication.translate("NewNodeDialog", "View/modify the fields of the node", None, -1))
        self.editFieldsBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "&Edit fields", None, -1))
        self.fieldsGB.setTitle(QtWidgets.QApplication.translate("NewNodeDialog", "Fields", None, -1))
        self.removeFieldBtn.setToolTip(QtWidgets.QApplication.translate("NewNodeDialog", "Remove selected field", None, -1))
        self.removeFieldBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "-", None, -1))
        self.addFieldBtn.setToolTip(QtWidgets.QApplication.translate("NewNodeDialog", "Add a new field", None, -1))
        self.addFieldBtn.setText(QtWidgets.QApplication.translate("NewNodeDialog", "+", None, -1))

import Resources_rc
