
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-18T22:02:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd8ad5a80fd43b632899ca88b9ebdbfd45170fe5",
 "version": "v0.6.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
