__title__ = 'weasl-sdk'
__description__ = 'Python SDK for weasl.in'
__url__ = 'http://docs.weasl.in'
__version__ = '0.0.2'
__author__ = 'Ryan Baker'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2018 Ryan Baker'