language: python
sudo: false
dist: xenial
os:
- linux
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -U pip
- pip install -U setuptools
- pip install -U tox
- pip install -U tox-travis
- pip install python-coveralls
- pip install coverage
script:
- tox -v --recreate
after_success:
- coveralls
deploy:
  provider: pypi
  user: levinoecker
  password:
    secure: mWmOYbIXbEDunP72CPScobzS1+q+vow/K+sQnCVtl6As5klMT3C3cUlORgHhVPmn2bEY01APMZRXRXjD4DdoYj4HGbzm/DJ7vXD7q3VA3GWkYf0M3UOZ2Ea6hg4rRP3sqJP9JCSs5uWN1EBWZZs1L4zfu00d1WaTTFn+5723K0hwJJQsIPobFzXc+1bkGvhRFZc7JTVBYWWQWm98B14sYw5KwvEfAJp8rCTIiw6BGaL9LYtEVkoQQXcf3fORFz7fwfayPiRWDTwDIUTa/JPjwdWUkL7LlK42HbsIpl02ojsdFyRecXC6/1bj8Owp6tXjti1gxOZkhuwhhohjZ8vzzzBGidGZYZfI5YdPBVKvTpVimCyZACLVh0eQ68Td76V97l46e8yVtE/2MRTUmkNUHrTq3e2H3jJTuLPlsRbsfsVmYUabzGyo/lqzz9nfqVkLkkh5zS8PGGwQo/K5GmiVtlMzSh9tnXV5CpxJpmp4BkvChpMmlrTb1KTCnsjO+/DUahuNm6u3osQPC7ZFAs5NkEgvKhn4UD1pryEf0IaDUXcTaWnF3LfeSYX09dqMPnX4dkaXb1jTsGmmnPSWLiIhJ6yNkhQfzbDGvaWhEAj6GgIFPIC5M0wI6MMuv3xExAWSQ5MdUHFMJJ3JIK3BRo4BYoSzd5C9EEFfgrG2RXbSMWw=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: '3.7'
