[tool.poetry]
name = "testclick"
version = "0.1.0"
description = ""
authors = ["saiteja <saitejapakalapati.a4@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
helloworld2 = 'testclick:helloworld.hello'
helloworld3 = 'testclick:helloworld.hello2'