
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-24T11:43:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "abfcf997515b460d390fb3d7d9fd0ce808160a4d",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
