
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-03T16:51:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a51a67c02716f4ace9f5b5c5589c0f9e3b86a3f",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
