language: python
sudo: required
dist: xenial
python:
- '3.7'
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: VtzmfhgA+fjTsqxDfnGtUhEuVUvxtLaFNcuSXCIKqnR42JhyCpUKXxSY8hPJHovgNogL0ryiMqjhKZIjalec+EaEkIhKDEXww8WAszwmkgElJTF05CGlzaFNnxqYwVjJlHUY2Z520yQnyJ+GRJIzYuSF3P4jWNU+55aexCFKp0gdbaC/AU3fzv0eLgSM/YG+SVyEiHmlm0FjJGQLbIvhuAlfzU8FWqtB27wh3mrevL74Nd1hp00VxlSyUxtMKwkzihvBdf2a7xXZVWwfHVlohR57MjMRawK65WlqjmnS7sxEO/E1shet6K1yNWsmWomLCQZZCjpY/Zd1IuM+hLt9yfrhsd+OdQJ+7AOfCEaojnLcnBZsJnw1QijBLJ/TJTOIBTCMhJCTN6YkprYBKcq8d+aWha9X3H/Vm0b1akK7ulkqY57ueWVSNcQmclB5AuPtb4vbxktpa7xzoVyPB4+bncsYv/94+XAOeWm0/ld3xXdjfWVhG4oM0GG5Un5+M3/A0zOCZeqvPBNwCtkAVLJ17z/xMC9jbNIKjD3EoosjsZ9qD57nDhZK3a+DxVclga1F2FHi96OAhDSvHdagPWF2qCvGp0gEkKx0PkFinTTwY11BJTFKFCZ2Xlmy7KLBCj+Dzs8VpTZuF34ow66tMtEENkd8DbSPV+E5t3zvi9o4V6U=
