
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-31T17:18:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "63eab4c85d83dc3e65eb8d14b8b4afe3db1286b7",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
