
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-23T17:14:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d42d64b9b1f1c07c22ac8cdf380111a499a3bb99",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
