version: '2'
services:
  policyserver:
    build:
      context: .
    links:
      - metadataserver:metadata
    ports:
      - 8181:8181
    environment:
      METADATA_PORT: tcp://metadata:8121

  elasticdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    environment:
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.watcher.enabled=false
    - http.cors.enabled=true
    - "http.cors.allow-origin=\"/.*/\""
    - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
    - "http.cors.allow-headers=\"X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization\""
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
      - 9300:9300

  metadatadb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: metadata
      POSTGRES_DB: pacifica_metadata
      POSTGRES_USER: pacifica
    ports:
      - 5432:5432

  metadataserver:
    image: pacifica/metadata
    links:
      - metadatadb:postgres
      - elasticdb:elasticdb
    ports:
      - 8121:8121
    environment:
      ELASTICDB_PORT: tcp://elasticdb:9200
      PEEWEE_DATABASE: pacifica_metadata
      PEEWEE_USER: pacifica
      PEEWEE_ADDR: postgres
      PEEWEE_PORT: 5432
      PEEWEE_PROTO: postgres
      PEEWEE_PASS: metadata
      METADATA_CPCONFIG: /usr/src/app/server.conf
