
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-05T10:26:19-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "26b4c2dd0dd4b82114c206fa339f4000f14ca5ec",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
