
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-01-24T10:55:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "3332a0ebd0ea810896693a7915ede6a9d9e0bd52",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
