kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app }}-front
spec:
  type: {{ .Values.front.service.type }}
  ports:
  - name: front
    port: {{ .Values.front.service.externalPort }}
    targetPort: {{ .Values.front.service.internalPort }}
    protocol: {{ .Values.front.service.protocol }}
  selector:
    app: {{ .Values.app }}
    role: front
    heritage: {{ .Release.Service }}
