# Generated by Django 2.0.6 on 2018-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20180818_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignemailtemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='campaignemailtemplate',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
