# Generated by Django 2.0.6 on 2018-10-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20180926_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmscampaign',
            name='image',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mmscampaign',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/mms'),
        ),
        migrations.AddField(
            model_name='mmscampaign',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/mms'),
        ),
        migrations.AddField(
            model_name='voicecampaign',
            name='voice_greeting_converted',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/sample_test_voice'),
        ),
        migrations.AddField(
            model_name='voicecampaign',
            name='voice_greeting_original',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/sample_test_voice'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='email_for_sample',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mmscampaign',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/mms'),
        ),
        migrations.AlterField(
            model_name='smscampaign',
            name='send_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
