# Generated by Django 2.0.6 on 2018-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20181013_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=25),
        ),
    ]
