# Generated by Django 2.0.6 on 2018-10-18 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_design', '0002_templatedesign_name_slug'),
        ('campaigns', '0005_emailcampaign_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='premium_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template_design.TemplateDesign'),
        ),
    ]
