# Generated by Django 2.0.6 on 2018-11-02 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_emailcampaign_premium_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='iemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        )
    ]
