# Generated by Django 2.0.6 on 2018-11-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20181102_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='osms',
            name='is_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.ISMS'),
        )
    ]
