# Generated by Django 2.0.6 on 2018-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_auto_20181128_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovoicecall',
            name='recording',
            field=models.FileField(null=True, upload_to='calls/recordings'),
        ),
    ]
