# Generated by Django 2.0.6 on 2018-12-18 23:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_auto_20181211_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osms',
            name='from_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osms',
            name='to',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='samplevoicecall',
            name='sample_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
