# Generated by Django 2.0.6 on 2018-12-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20181218_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovoicecall',
            name='recording_sentiment_magnitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ovoicecall',
            name='recording_sentiment_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ovoicecall',
            name='recording_text',
            field=models.TextField(blank=True, null=True),
        )
    ]
