# Generated by Django 2.0.6 on 2019-01-03 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_auto_20181229_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupdetail',
            name='custom_delay',
            field=models.IntegerField(blank=True, help_text='This is the delay before sending after the lead is captured', null=True),
        ),
        migrations.AddField(
            model_name='followupdetail',
            name='custom_delay_unit',
            field=models.CharField(blank=True, choices=[('4', 'Seconds'), ('3', 'Minutes'), ('1', 'Days'), ('2', 'Hours')], help_text='This is the unit of the delay before sending after the lead is captured', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalfollowupdetail',
            name='custom_delay',
            field=models.IntegerField(blank=True, help_text='This is the delay before sending after the lead is captured', null=True),
        ),
        migrations.AddField(
            model_name='historicalfollowupdetail',
            name='custom_delay_unit',
            field=models.CharField(blank=True, choices=[('4', 'Seconds'), ('3', 'Minutes'), ('1', 'Days'), ('2', 'Hours')], help_text='This is the unit of the delay before sending after the lead is captured', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='delay_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='followupdetail',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign'),
        ),
        migrations.AlterField(
            model_name='mmscampaign',
            name='delay_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smscampaign',
            name='delay_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='voicecampaign',
            name='delay_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
