[tool.poetry]
name = "silverbullet"
version = "0.3.0"
description = "shallow but powerful wrapper around pybullet"
authors = ["coord.e <me@coord-e.com>"]
license = "MIT"
readme = 'README.md'
repository = 'https://github.com/MonoMotion/silverbullet'
homepage = 'https://github.com/MonoMotion/silverbullet'

[tool.poetry.dependencies]
python = "^3.7"
pybullet = "^2.4"
numpy = "^1.16"

[tool.poetry.dev-dependencies]
flake8 = "^3.6"
autopep8 = "^1.4"
mypy = "^0.660.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
