[tool.poetry]
name = "starlette-api"
version = "0.3.2"
description = "Starlette API layer inherited from APIStar"
authors = ["José Antonio Perdiguero López <perdy@perdy.io>"]
license = "GPL-3.0+"
readme = "README.md"
repository = "https://github.com/PeRDy/starlette-api"
keywords = ["starlette", "api", "apistar", "components", "schema"]
include = []
exclude = []

[tool.poetry.dependencies]
python = "^3.6"
starlette = ">=0.9.10"
marshmallow = {version = ">2",allows-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^3.6"
pytest-xdist = "^1.22"
pytest-cov = "^2.5"
tox = "^3.0"
clinner = "^1.10"
ipython = "^6.4"
requests = "^2.19"
ipdb = "^0.11.0"
black = "^18.3-alpha.0"
isort = "^4.3"
python-multipart = "^0.0.5"

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | build
  | dist
)/
'''
