
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-28T13:54:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "462fcb91045ab0dbb5ff27daa4154831e1c1624b",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
