
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8ff3fda3bb6f062f2521e2a4b0f28f545819e627",
 "version": "0.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
