
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-02-01T18:04:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e8c379b3636c64707e7a08b8eb6c9af20a1ac4d",
 "version": "2019.2.1.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
