# Generated by Django 2.0.6 on 2018-09-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ACCOUNT_USER_PROXY_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('token', models.CharField(max_length=500)),
                ('token_type', models.CharField(max_length=100, null=True)),
                ('type', models.IntegerField(choices=[(1, 'User'), (2, 'Page'), (3, 'Group')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('expires', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.ACCOUNT_USER_PROXY_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='34f33541-2353-43d2-9843-053855c29634', max_length=100)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.ACCOUNT_USER_PROXY_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=500, null=True)),
                ('middle_name', models.CharField(max_length=500, null=True)),
                ('last_name', models.CharField(max_length=500, null=True)),
                ('about', models.CharField(max_length=500, null=True)),
                ('link', models.URLField(null=True)),
                ('access_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook.AccessToken')),
            ],
        ),
    ]
