# Generated by Django 2.0.6 on 2018-11-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0004_auto_20181102_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authstate',
            name='code',
            field=models.CharField(default='45bf8504-3878-49be-8b22-31f2f4eda626', max_length=100),
        ),
    ]
