# Generated by Django 2.0.6 on 2018-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20181107_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authstate',
            name='code',
            field=models.CharField(default='e0404472-4515-4aae-b169-380c1a7a4c22', max_length=100),
        ),
    ]
