
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-21T13:35:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1d4926ae35e8977e1abe5deafbe8101e509f020",
 "version": "1.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
