language: python
#python:
#  #  - "2.6"
#  - "2.7"
#  # - "3.2"
#  # - "3.3"
#  - "3.4"
env:
    - CONDA_PYTHON_VERSION=2.7
    - CONDA_PYTHON_VERSION=3.4
    - CONDA_PYTHON_VERSION=3.6
virtualenv:
    system_site_packages: false
before_install:
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$CONDA_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
#    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda create --yes -n travis python=$CONDA_PYTHON_VERSION
    - sudo apt-get install -qq $(< requirements_apt.txt)
    - "export DISPLAY=:99.0"
    - sh -e /etc/init.d/xvfb start
# command to install dependencies
install:
    - conda update --yes conda
    - conda install --yes -n travis pip nose coverage
    - conda install --yes -n travis --file requirements_conda.txt
#    - conda install --yes -n travis -c SimpleITK -c luispedro -c mjirik --file requirements_conda.txt
    - source activate travis
    - pip install -r requirements_pip.txt
    - conda info -a
    - conda list
# command to run tests
script: nosetests --with-coverage --cover-package=sed3
after_success:
    - coveralls
