# Generated by Django 2.1.5 on 2019-02-01 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katkaproject',
            name='base_url',
            field=models.URLField(default=settings.DEFAULT_BITBUCKET_SERVICE_LOCATION),
        ),
    ]
