
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ad1076c6f9fc321564bdc589d0893247a6203abc",
 "version": "1.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
