
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fce7a18f1a8b9d7669ee25e77d81812f9051997e",
 "version": "0.1.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
