language: python

sudo: required

matrix:
    include:
        - python: '2.6'
          dist: trusty
          sudo: false
        - python: '2.7'
          dist: trusty
          sudo: false
        - python: '3.1'
          dist: trusty
          sudo: false
        - python: '3.2'
          dist: trusty
          sudo: false
        - python: '3.3'
          dist: trusty
          sudo: false
        - python: '3.4'
          dist: trusty
          sudo: false
        - python: '3.5'
          dist: trusty
          sudo: false
        - python: '3.6'
          dist: trusty
          sudo: false
        - python: '3.7'
          dist: xenial
          sudo: true
        - python: 'nightly'
          dist: xenial
          sudo: true
        - python: 'pypy'
          dist: trusty
          sudo: false
        - python: 'pypy3'
          dist: trusty
          sudo: false
    allow_failures:
        - python: '2.6'
        - python: '3.1'
        - python: '3.2'
        - python: '3.3'
        - python: 'nightly'
        - python: 'pypy'
        - python: 'pypy3'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - sudo apt-get update -q
    - set -x; sudo apt-get install -y -q openmpi-bin libopenmpi-dev

install:
    - python setup.py build && python setup.py install

script:
    - for test in tests/*.py; do echo $test ; python $test > /dev/null ; done
