[tool.poetry]
name = "lissajous"
version = "0.1.2"
description = "A Lissajous Curve Visualizer written in Python"
authors = ["kosayoda <kieransiek@gmail.com>"]
license = "MIT"
repository = "https://github.com/kosayoda/lissajous"
readme = "README.md"
keywords = ["lissajous", "visualizer", "visualiser"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16"
matplotlib = "^3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
lissajous = 'lissajous.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
