---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s]: %(message)s'
  detailed:
    format: 'time=%(asctime)s level=%(levelname)s name=%(name)s msg=%(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: vigil.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: vigil_errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8 

loggers:
  vigil:
    level: DEBUG
    propagate: True

root:
  handlers: [console, debug_file_handler, error_file_handler]
