# Based on http://conda.pydata.org/docs/travis.html
language: python
#sudo: false # use container based build
notifications:
  email: false
dist: xenial

matrix:
  fast_finish: true

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

env:
  - CONDA_PACKAGES="codecov pytest"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

install:
  - |
      echo ""
      echo "Configuring conda."
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install conda-build
      conda info -a

script:
  - conda-build conda-recipe
