package:
  name: intake-avro
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
  run:
    - intake>=0.3
    - pandas
    - dask
    - uavro
    - fastavro

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_avro tests

about:
  home: https://github.com/ContinuumIO/intake-avro
  license: BSD
  license_file: LICENSE
  summary: Intake avro plugin
