
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-04T20:21:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f9da561ee64f906f0d13f2c507c91fa80ec3de5",
 "version": "v0.5.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
