# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-05 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoanalytics', '0002_auto_20190123_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawhit',
            name='hit_type',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='rawhit',
            name='session_medium',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_session_medium',
            field=models.TextField(default='unknown'),
        ),
    ]
