
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-23T17:12:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "181e6c3b581327ad1f5d0dcd04982b24cffd622e",
 "version": "1.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
