
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-27T00:30:52-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed1d5242ce387f026f97f6ae71e323ec41138dbd",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
