
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-28T13:27:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ecf41ae16f7d15a93becc096ba8296f225808308",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
