language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

script:
  - python -m unittest

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: LGH1ewSFCKfr+xljOxT2Z1oCgfyCchf5QTvh1Q7sXuJMtkkCpdgAfUdCA/Ng9OseD1BcT5cMtDP/j+C0zimld6ZOFEvtfZqhXgViuMA8h1QRr/GgCGFGKzqnoqY+hTuvJ+fBUr7LBShWuD0wTCKD3r66R+gB2wmlgC08G//M7z3ZLdxXFDH1EmnB69Smfch65stqF7l8zinFp+FasuqnrLniXxmBLoXiMepQeKUBfNhRU4J6J7/b5apk1IZIOeDoR8zq+DROv/YRtGxByCHAIIRgz4ovnfgnYdjWOPT8Al6ruTOYsibYiFBZBrKpJ7b5bdc3jPmyhS69CX+XWeIR+Bp3AxtEMqeVErmTcpdBqWTaFpUyO+fF5+he8aTzn7FkXC7X8ChZeA96RzPssgORZnKngThI67VnamZYr8ArGTAdRZRE2e3Ek7gHISEtJuTVxwCtUTOvK2GvRdH7ewJuuHmdIRbOmpoJRZYfOGcz6nwlpcxkeMQmW4UzNdoMOgZFXeXDWDc8RsNCqX5oJhISCeIC2ytz8nF/gAgpHLHqv0pSFn5DkIIG2cNdNAR1V8GtXwRR17JdAB1PqN6gJ2VQyBTCsqOc9ME0Fr/EXqPisZwwqDs9oYAhMAMBqtKrx6oAtzSVCGbiZ3m3I9XYhukOptSu8F6UQDXaEaKE9JM15sE=
  on:
    tags: true
    repo: internap/jabstract
