# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(blank=True, choices=[('event', 'Обычное обращение'), ('return', 'Возврат'), ('payment_notification', 'Сообщение об оплате')], default='event', help_text='Тип обратной связи', max_length=30, verbose_name='Тип обратной связи')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('name', models.CharField(help_text='Наименование обращения', max_length=255, verbose_name='Наименование обращения ')),
                ('email', models.EmailField(default='', help_text='Адрес, на который будут приходить собщения с данным типом. Например, сообщения с типом "Сообщить об оплате" должны приходить сотруднику финансовой (службы).', max_length=255, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Тип обратной связи',
                'verbose_name_plural': 'Типы обратной связи',
                'db_table': 'feed_back_type',
            },
        ),
    ]
