# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=1, verbose_name='ID покупателя')),
                ('file', models.FileField(upload_to='feedback_files/')),
            ],
            options={
                'verbose_name': 'Файл покупателя',
                'verbose_name_plural': 'Файлы покупателей',
                'db_table': 'feedback_files',
            },
        ),
    ]
