# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem_feedback', '0002_feedbackfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Ваш email')),
                ('subject', models.CharField(default='', max_length=255, verbose_name='Тема обращения')),
                ('message', models.CharField(default='', max_length=255, verbose_name='Обращение')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='stem_feedback.FeedBackType', verbose_name='Тип обратной связи')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'db_table': 'feedback',
            },
        ),
    ]
