# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import stem_feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('stem_feedback', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='email пользователя')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('message', stem_feedback.models.JSONField()),
                ('sent', models.BooleanField(default=False, verbose_name='Синхронизация с учетной системой')),
            ],
            options={
                'verbose_name': 'Сообщение об обратной связи',
                'verbose_name_plural': 'Сообщения об обратной связи',
                'db_table': 'feedback_message',
            },
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('event', 'Обычное обращение'), ('return', 'Возврат'), ('payment_notification', 'Сообщение об оплате'), ('callback', 'Перезвонить')], default='event', help_text='Тип обратной связи', max_length=30, verbose_name='Тип обратной связи'),
        ),
    ]
