
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "20f0f7b705f662db2e7009d8332fc7bd98a08fb8",
 "version": "0.4.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
