[tool.poetry]
name = "pokemaster"
version = "0.1.0"
description = ""
authors = ["Kip Yin <kipyyin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pokedex = { git = "https://github.com/veekun/pokedex.git", branch = "master" }
sqlalchemy = "^1.2"
attrs = "^18.2"
construct = "2.5.3"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
black = { version = "^18.3-alpha.0", allows-prereleases = true }
mypy = "^0.650.0"
pre-commit = "^1.12"
pytest-cov = "^2.6"
isort = "^4.3"

[tool.black]
line-length = 80
py36 = true
skip-string-normalization = true
skip-numeric-underscore-normalization = true

[tool.isort]
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
