# Generated by Django 2.0.6 on 2018-09-25 18:34

from django.db import migrations, models

from slugify import slugify


def update_slug_name(apps, schema_editor):
    TemplateDesign = apps.get_model('template_design', 'TemplateDesign')
    for temp_desgn in TemplateDesign.objects.all():
        temp_desgn.name_slug = slugify(temp_desgn.name)
        temp_desgn.save()


class Migration(migrations.Migration):
    dependencies = [
        ('template_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedesign',
            name='name_slug',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.RunPython(update_slug_name)
    ]
