language: generic
dist: xenial
services:
- docker
env:
  global:
  - secure: RLZpoFMSnDk2OYS/f8f47yRySB7dyOKJb96qgylp4Jw48UZ5ktswxDEAIdBjIvX6mi9MTTbaCFIvrdAAxH8qbOkWY3usi9DTpvJlbZNpKw+C08m+x5leR+OZohOPAQGXaGP617nqslcqC6BMI01gxz45BPi3nj/gyoNR4Te5bPsRQHyPAOIUJ1pxSXnpg8a48kc4XmrvJgTxAQFQ0upQwVFfOCm6pqZCrMl3posOWBP3R+BKZ/tWMylg8go1D1F1JJ4Ef8x7WQiZ/w3CjSLD3+P+29vRDzO0Xe7LWkgAOCeUmB8lzmmlHXluPRxiIAp7ACFTdHaA4Y1TQjA/2rnwoeAyZ27jF9NHNiIgKJ17H4HwBZ01OLA5PgW2NZSqjJ82W4huF6Uz50J3c3ojkiD/WinCc7Gh8oWck+fSFoXc3PJO2vioPb6YT/tJog+xwiSBRauqB1ihTkxAbf5YZsrZeYyNRT/Uc30QUpozTcXqsWSnMxZxn4+RGY/TzyVIqVW0SJ8SCTJ1tPRsq1GEli0XaPyFBYdkZ4BHNQKBGg5TbGOKjrKV66FMlEeFokSjGUVM2Swwz3g7ksUYqxhjvF1vQnQFcisLMkVuz0MNfeQPS93tVbG3+O8qn+PhMzEShpTMXMofstvB6EHSG7l0p6t1BOYRmiLIaPBbnL8q6VQn10k=
  matrix:
  - DEBIAN_VERSION=jessie STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS=""
  - DEBIAN_VERSION=stretch STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=10.2.5 --dh-compat=10"
  - DEBIAN_VERSION=buster STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.5.2 --dh-compat=11"
  - DEBIAN_VERSION=xenial STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS="--dh-min=9.20160115ubuntu3 --dh-compat=9"
  - DEBIAN_VERSION=bionic STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.1.6 --dh-compat=11"
before_install:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export REPO=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_REPO_SLUG;
  else echo $TRAVIS_PULL_REQUEST_SLUG; fi)
- echo "REPO=$REPO, TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- openssl aes-256-cbc -K $encrypted_e060ef17c1b2_key -iv $encrypted_e060ef17c1b2_iv
  -in secret_key.asc.enc -out /tmp/secret_key.asc -d
- mkdir -p /tmp/output
- chmod 777 /tmp/output
- docker pull ashleysommer/stdeb3:$DEBIAN_VERSION
before_script:
- docker run -v $(pwd)/docker-script.sh:/home/stdeb3/docker-script.sh  -v /tmp/secret_key.asc:/tmp/secret_key.asc
  -v /tmp/output:/home/stdeb3/output -e GPG_SECRET_KEY="/tmp/secret_key.asc" -e GPG_SECRET_KEY_PASSPHRASE="${GPG_SECRET_KEY_PASSPHRASE}"
  -e PYTHON_PROJECT_GIT="https://github.com/${REPO}.git" -e PYTHON_PROJECT_BRANCH="${BRANCH}"
  -e STDEB3_SIGN_RESULTS="$STDEB3_SIGN_RESULTS" -e STDEB3_EXTRA_ARGS="$STDEB3_EXTRA_ARGS"
  -t -i ashleysommer/stdeb3:$DEBIAN_VERSION
- ls -lah /tmp/output
deploy:
  provider: releases
  api_key:
    secure: gSe6qxu8eoGz3vjhBBmFFdoSgfA217+C7F7H+wjwyG8gOEVv5I9HoJ3YvPGJpT2Wg343pFbbM16v5u/N9JB6KHCsrY2Qt0LIhoq+fsayTvf12zeWJ8CNAn3IJ3HUExowKwd0YSNEgxRmQhwaUT3jzNEQvymqpvxGiBcYwtN8wMrz7kJowNx2vTHPZ5UH/KypZoWZT1Eag1CXrPeEC0NS4kbRiuWMpKMkkz0kkWJjdmW4on/r+aIHpeM89qVlNqem5pFzInrRMvjQynGPRp9XxKtJ5Hpzhdjj2msc8t6s43lUCQMcKTUC2XpDebPbjHwzEwXh6iNwB+WG/8xdbxU4Jy6/jXkrxal5tjvJ0PbRNSM5M25qgNPIpoRSL4i6bjanLIap0I7q1LwYa3HrBXS2nsVX6e+v3LbNKQZjcsFHUZHldyrCXaVvguobB7pvP0/T10Gkqx+9uD49QRuJs6kpvCIwjqG/VAQnmS9dC8SLBvMZIvlk/iSyfTW3NvANIcPUr3NnzPlctIRAYcTPLdSN5s8mBRsuJL1CSUQdXHkVbWBzVBltQVh5FdSIbAFy5h+hvJmPJNXeDApocF+VAMbft7djE496zbrwxeqniZZuyBI8U//bjdKyHWPBYLpvkGeb9C9nfcZ6fTvjOpLFWNNssmerrtUSJ8jq0sv1rAHFfig=
  overwrite: true
  file_glob: true
  file: /tmp/output/*.deb
  skip_cleanup: true
  on:
    tags: true
