
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a42fe556504c7395ed2a9b9a27b880e63455c121",
 "version": "2063"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
