language: python
sudo: required
dist: xenial
python:
  - '3.7'
  - '2.7'
  - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: B0ouF6E/+0aWTP+f7NhOZkBO4WSoxNsphkua9epaEc7ymgpQ9MX1XJI7BCoap8JCXW8TPdSBTwWxm5fpj8hOS+S7L5fg2cgyn9FJs98x35m0CBcoI2IgfDnSahKlhikd/t87tovgfiBLth10O8v7h/EvkSKf7R9FjTYeDgmZGHQY42o3CDoCYD+Bto+PFFJSt3o6tm0O9s/fsOkDPSAQMTHQW+FnH5jATsIVv6fiMPYxJO5Iosjx8SW6Drj/uwX/pp16btoFneqVgYJHAuFLbumGd5Akx8466DIurYvTGwD/efOExncCBVKQgyNQFY5rpFOMtfPW0v6s7ELpN8MX55QACdOxBhzha26N4LNME8kmiVRuqMJSZXjjQZ4/IXxR8PuFR82/uKcwxm4dHoMvrMU4iaWfOT5fhWZFXkBvWXxz5QtQr1Rjih0Dg+uhW5M+qmkekOoxDY2apdUvVEAKyjFukSTBfHOMyIYscuLRiLfTcluKeZGkqJDWtsGQsv9+t0TVLM8lAlGY371NalTAqRJC/S/r1qcgAuI9FoHWpO0xgjL+Z4u1fnQdlro6mnwIttCLXpxKXYQwguL/Xn+Uzm0XG/xdMsEI0mfgCEujgiQjnk5b5K39Ir9y33QT9Z7Lwqj/6vl6XigilwOWby79BkpJ7pxAmfca2ASggf0xiCQ=
