
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-30T14:30:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9aab1a3bc72f51b2a626d1582d286c333770b1fa",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
