
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-21T17:43:28-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0501462f94bdfc5ff62b2dfcb8b67d0268dcc13b",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
