networks:
  default:
    external:
      name: dy
services:
  ruby:
    image: quay.io/akretion/docky-ruby:latest
    volumes:
      - .:/workspace
      - $HOME/.docky/shared/bundle:/usr/local/bundle
version: '3'
