language: generic
dist: xenial
services:
- docker
env:
  global:
  - ENV1=test1
  matrix:
  - DEBIAN_VERSION=jessie STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS=""
  - DEBIAN_VERSION=stretch STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=10.2.5
    --dh-compat=10"
  - DEBIAN_VERSION=buster STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.1.6
    --dh-compat=11"
before_install:

- openssl aes-256-cbc -K $encrypted_e060ef17c1b2_key -iv $encrypted_e060ef17c1b2_iv
  -in secret_key.asc.enc -out /tmp/secret_key.asc -d
- echo "Gu1NVEmzDxzQIJwoHTB1r2afv99+7Pi2zSdOfId8vOYKHdB+m7QWlhLFCPNhsIAj2zQgAIpgBaILK9ugxbkipisj7R4hQTWQOgR03AqssAmNs39vDtMh52w5DrF5qVBVsZzuZBlD8lKZozxjmdMDcHt27/Jbp6fMkMMfrqibPOuajJafl9/YUloG+/iFwW7s2Z6T7/UCRp03LMTzN8RlEip696V2I1mRMx+yaiKjowPvNEY7LJ87CSnrmrC2Au5I2rTsAD+Kw/r7bnfkBhYWPnrsm17FLa1qa4+jAy3BcXEj/PLKqsBbMeyvjl6gIvFxqgqK3qMrgqCS2vjEAKfc0Fb22/4Uwd9ee5rc/7Am2A7xfS428ZsPZJaFafZ1BfNRNb26DCfgbbji7O6eecGv5E9vXeG2O0YefINdqZ3N9bK2zszbQqJoxiMK1vbsKsp7xYRQrTDptX/tBxyBLTteNXneeB+HboxWxXgp/S89rfMXuyrr3O+VZ+FtL79ypCvQsLuWo4QY09svRVsSThlKOuLUExscCbQraSU6ECLaqq4ZA4YgHH/TAmyJ7k5wV2lrW0cMIEaZnHPMA8JZsIAayP8GOCcpcvk14zv6XdmheH3ZMP8eaFgn3GC5Yv+DG8lYmsPqGfeOGfFPC21j1EeDOjnsOyiyylg4avzhAG+PHvE="
  | openssl aes-256-cbc -K $encrypted_e060ef17c1b2_key -iv $encrypted_e060ef17c1b2_iv -in /dev/stdin -out /tmp/secret_key_passphrase.txt -d
- mkdir -p /tmp/output
- chmod 777 /tmp/output
- docker pull ashleysommer/stdeb3:$DEBIAN_VERSION
before_script:
- docker run -v $(pwd)/docker-script.sh:/home/stdeb3/docker-script.sh  -v /tmp/secret_key.asc:/tmp/secret_key.asc -v /tmp/secret_key_passphrase.txt:/tmp/secret_key_passphrase.txt
  -v /tmp/output:/home/stdeb3/output -e GPG_SECRET_KEY="/tmp/secret_key.asc" -e STDEB3_EXTRA_ARGS="$STDEB3_EXTRA_ARGS"
  -t -i ashleysommer/stdeb3:$DEBIAN_VERSION
- ls -lah /tmp/output
deploy:
  provider: releases
  api_key:
    secure: R5nVWEUmG7Y2/Y1TNhwSQ0Qixv8ARPf78hkX1TNBkm49254S0tpcdHBCoSd0bpsLpMPtwh9OOE7wzY8ns1MwJ7ZKrx9H7Axi8q2WeFaiV7zwIfd3WThviYJ40dKtCuDX2m88jZgE1/bF8MRKr2rVBLPfS5O8FK+ZcmEUV5L71CFYAR0zVo/6G94GXNTw44UhNFgkSWtDJuhPVYGtnvUCVkMtv4ymFgwAtSww0rJ82sdphND5cn25T5G9RdePTQkki3MM5d29uDEGVP244baiQkyTt0XjtltNX+HdpX3A2TFRtT54gdypnElU2WfEHjUaoCYKZ++/+F1xlYwKtIWx+QSv3qILrKTc6+3rFVryp541k4Q34Ox5vsYUXpu2O91AhhXYrwkmhyAYPQftslP/yxc0xMogpabX38BX0HZ4N4+fUcelkW9LiIxv7qT266f+kvCtSwdi8NMrpnlWliooGX33fOXIb3Gh21xO56yM804S2x+cU9qvjlH6ktzZJ5NDTRESTfMUNQ5jsKRjdotQpiDOsZLySsPycEOJioUe+qtazQ3pdaWXLyiuQ7eADrZOYledY1jX8ojo8NK9ZG5VsZYpgRFjEkKJLsMCrJTm8I1DuMSo0PU9Te0+meKRNQBG2CyuObig7XEgPYdRAfst4Ri9hTf2/gcWbunqrI6GVOc=
  file: "/tmp/output/*.deb"
  skip_cleanup: true
  on:
    tags: true
