[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "aria2p"
version = "0.2.0"
description = "Command-line tool and library to interact with an aria2c daemon process with JSON-RPC."
license = "ISC"
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
readme = 'README.md'
repository = "https://github.com/pawamoy/aria2p"
homepage = "https://github.com/pawamoy/aria2p"
keywords = ['aria2', 'aria2c', 'aria2-cli']
packages = [ { include = "aria2p", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
ipython = "^7.2"
recommonmark = "^0.4.0"
sphinx = "^1.8"
sphinx-rtd-theme = "^0.4.2"
sphinxcontrib-spelling = "^4.2"
responses = "^0.10.5"
pytest-coverage = "^0.0.0"
pytest-xdist = "^1.26"
flake8 = "^3.6"

[tool.poetry.scripts]
aria2p = 'aria2p.cli:main'

[tool.black]
line-length = 120

