# Generated by Django 2.0.6 on 2019-01-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_auto_20181230_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetype',
            options={'ordering': ('ordering',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='purchasedpackage',
            options={'verbose_name': 'Purchased Package', 'verbose_name_plural': 'Purchased Packages'},
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='In Stripe this is the amount', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='phones',
            field=models.IntegerField(blank=True, default=0, help_text='Amount of phone numbers included in the Plan', null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='sku',
            field=models.SlugField(help_text='Stock Keeping Unit. A specific product variation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='title',
            field=models.CharField(help_text='Nickname in Stripe.', max_length=255),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='type',
            field=models.CharField(choices=[('1', 'Recharge'), ('2', 'Registration')], default='1', max_length=1),
        ),
    ]
