# Generated by Django 2.0.6 on 2019-01-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190104_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twilionumber',
            options={'verbose_name': 'Purchased Twilio number', 'verbose_name_plural': 'Purchased Twilio numbers'},
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Stripe amount.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='email',
            field=models.IntegerField(blank=True, default=0, help_text='EMAIL', null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='mms',
            field=models.IntegerField(blank=True, default=0, help_text='MMS', null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='sku',
            field=models.SlugField(help_text='Stripe plan ID. this is autogenerated automatically.', max_length=255),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='sms',
            field=models.IntegerField(blank=True, default=0, help_text='SMS', null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='talktime',
            field=models.IntegerField(blank=True, default=0, help_text='VOICE', null=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
