%YAML 1.2
---

# logging config for pywisp package
version: 1
disable_existing_loggers: true

# default logger
root:
  level: !!python/name:logging.NOTSET
  handlers: [console]

handlers:
  # display some data on cmd-line
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simpleFormatter
    level: !!python/name:logging.NOTSET

formatters:

    simpleFormatter:
      class: logging.Formatter
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

#    commandlineFormatter:
#      class: !!python/name:logging.Formatter
#      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
#      datefmt: '%d/%m/%Y %H:%M:%S'
...
