
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-30T13:59:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5b4e294dd39317c78fee792adf96fef84913486",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
