# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labadmin', '0008_logaccess_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerror',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labadmin.Device'),
        ),
    ]
