REQUIRED_PERMISSIONS = [
    'email',
    # 'groups_access_member_info',
    'publish_to_groups',
    # 'user_age_range',
    # 'user_birthday',
    # 'user_events',
    # 'user_friends',
    # 'user_gender',
    # 'user_hometown',
    # 'user_likes',
    # 'user_link',
    # 'user_location',
    # 'user_photos',
    'user_posts',
    # 'user_tagged_places',
    # 'user_videos',
    'manage_pages',
    # 'pages_manage_cta',
    # 'pages_manage_instant_articles',
    # 'pages_show_list',
    # 'pages_messaging',
    # 'pages_messaging_phone_number',
    # 'pages_messaging_subscriptions',
    'publish_pages',
    # 'publish_video',
    # 'read_page_mailboxes',
    'business_management',
]
