[tool.poetry]
name = "tedent"
version = "0.1.0"
description = "like dedent but more flexible"
authors = ["Philip Olson <philip.olson@pm.me>"]
readme = "README.md"
repository = "https://github.com/olsonpm/py_tedent"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
wrapt = "^1.11"
ordered_set = "^3.1"

[tool.poetry.dev-dependencies]
case_conversion = "^2.1"
simple_chalk = "^0.1.0"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
