os: linux

dist: xenial

# Prefer docker containers
sudo: required

language: python

python:
  - "3.7"

cache: pip

addons:
  apt:
    packages:
      - patchelf

env:
  global:
    - TWINE_USERNAME=phd
    # Note: TWINE_PASSWORD is set in Travis settings.
    #- TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    env: TOXENV=py37
  - python: "2.7"
    env: TOXENV=py27-flake8
  - python: "3.7"
    env: TOXENV=py37-flake8
  - python: "pypy2.7-6.0"
    env: TOXENV=pypy

  fast_finish: true

install:
  - travis_retry pip install --upgrade "pip < 19.1" setuptools tox ppu

script:
  - tox

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip

deploy:
  provider: script
  script: devscripts/CI/travisci-release
  on:
    tags: true
