[tool.poetry]
name = "libtvdb"
version = "0.3.0"
description = "A wrapper around the TVDB API."

license = "MIT"

authors = [
    "Dale Myers <dale@myers.io>"
]

readme = 'README.md'

repository = "https://github.com/dalemyers/libtvdb"
homepage = "https://github.com/dalemyers/libtvdb"

keywords = ["tvdb", "tv", "tv database", "tv show"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = "^3.7"
deserialize = "=0.7.0"
keyper = "=0.3"
requests = "=2.20.1"

[tool.poetry.dev-dependencies]
mypy = "=0.641"
pylint = "=2.1.1"
pytest = "=4.0.1"
pytest-cov = "=2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
