# Generated by Django 2.0.6 on 2018-11-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_to_call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatemasterlist',
            name='is_import_complete',
            field=models.BooleanField(default=False),
        ),
    ]
