# Generated by Django 2.0.6 on 2018-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_to_call', '0002_associatemasterlist_is_import_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwimlApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
