# Generated by Django 2.0.6 on 2018-12-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('click_to_call', '0003_twimlapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('sms', 'Text Message'), ('voice', 'Voice Message')], default='voice', max_length=5)),
                ('audio', models.FileField(null=True, upload_to='calls/personalized')),
                ('text', models.CharField(default='', max_length=1000)),
                ('audio_processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
