version: '3'
services:
  proxyserver:
    build:
      context: .
    links:
      - metadataserver:metadata
      - archivei:archiveinterface
    ports:
      - 8180:8180
    environment:
      METADATA_URL: http://metadata:8121
      METADATA_STATUS_URL: http://metadata:8121/groups
      ARCHIVEINTERFACE_URL: http://archiveinterface:8080

  archivei:
    image: pacifica/archiveinterface
    ports:
     - 8080:8080

  elasticdb:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    environment:
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.watcher.enabled=false
    - http.cors.enabled=true
    - "http.cors.allow-origin=\"/.*/\""
    - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
    - "http.cors.allow-headers=\"X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization\""
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  metadatadb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pacifica_metadata
      POSTGRES_USER: metadata
    ports:
    - 5432:5432

  metadataserver:
    image: pacifica/metadata
    links:
    - metadatadb:postgres
    - elasticdb:elasticdb
    ports:
    - 8121:8121
    environment:
      ELASTICDB_PORT: tcp://elasticdb:9200
      PEEWEE_DATABASE: pacifica_metadata
      PEEWEE_USER: metadata
      PEEWEE_ADDR: postgres
      PEEWEE_PASS: password
      PEEWEE_PROTO: postgresql
      METADATA_CPCONFIG: /usr/src/app/server.conf
