[tool.poetry]
name = "carly"
version = "0.9.1"
description = "A tool for putting messages into and collecting responses from Twisted servers using real networking"
authors = ["Chris Withers <chris@withers.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"
Twisted = "^18.9"
attrs = "^18.2"

[tool.poetry.dev-dependencies]
testfixtures = "^6.3"
autobahn = "^18.11"
coverage = "<5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
