
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-06T16:42:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ccb1ced23ad740f7c7c0e9a5a312643f125c1599",
 "version": "0.1.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
