- job:
    name: os-vif-ovs
    parent: legacy-dsvm-base
    run: playbooks/os-vif-ovs/run.yaml
    post-run: playbooks/os-vif-ovs/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/nova
      - openstack/os-vif
      - openstack/tempest

- project:
    templates:
      - check-requirements
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - kuryr-kubernetes-tempest-daemon-octavia:
            voting: false
        - openstack-tox-functional-with-sudo
        - os-vif-ovs
    gate:
      jobs:
        - openstack-tox-functional-with-sudo
        - os-vif-ovs
