
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-05T14:01:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5064284550f663a98c9a649239d3d9e501203eb",
 "version": "0.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
