
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-09T13:07:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ae43a5bd3e3bff1758399ce1590eca1846a1f6c",
 "version": "1.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
