# Version file autogenerated by the build process
version = '0.6.0rc2'
build = '237'
vcs_info = 'Git SHA1 f7840afe committed on 2019-02-05'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.6.0rc2"\nKSCONF_BUILD="237"\nKSCONF_VCS_INFO="Git SHA1 f7840afe committed on 2019-02-05"')
