[tool.poetry]
name = "ap-mal"
version = "0.1.0"
description = "Import and Export of lists between Anime-Planet and MyAnimeList"
authors = ["Christopher Goes <ghostofgoes@gmail.com>"]
license = "LGPL 2.1"
readme = "README.rst"
repository = "https://github.com/GhostofGoes/ap-mal"
keywords = ["anime-planet", "myanimelist", "anime", "manga", "export"]

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.7"
requests = "^2.21"
lz4 = "^2.1"
keyring = "^17.1"
pycryptodome = "^3.7"
pywin32 = {version = "^224.0",platform = "win32"}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
pytest-random-order = "^1.0"
pytest-cov = "^2.6"
codespell = "^1.14"
flake8-bugbear = "^18.8"
flake8-import-order = "^0.18.0"
flake8-tidy-imports = "^1.1"
flake8-todo = "^0.7.0"
flake8-string-format = "^0.2.3"
bandit = "^1.5"
flake8-mypy = {git = "https://github.com/ambv/flake8-mypy.git"}

[tool.poetry.scripts]
ap-mal = 'ap_mal.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
