from distutils.core import setup
setup(
  name = 'cercatrova',         
  packages = ['cercatrova'],   
  version = '0.4',      
  license='MIT',        
  description = 'metadata extraction and transaction',   
  author = 'Cerca Trova',                   
  url = 'https://github.com/KathHv/geosoftware2_ct',   
  download_url = 'https://github.com/KathHv/geosoftware2_ct/archive/v_01.tar.gz',   
  keywords = ['Python', 'metadata', 'extraction'],   
  install_requires=[   
          'fiona==1.8.4',
          'netCDF4==1.4.2',
          'pyshp==2.0.1',
          'pygeoj==1.0.0', 
          'dicttoxml==1.7.4',
          'geojson==2.4.1',
          'pytest==4.0.2',
          'Shapely==1.5.17',
          'six==1.10.0',
          'django==2.1.5',
          'pyproj==1.9.5.1',
          'lxml==4.3.0',
          'iso8601==0.1.12',
          'numpy==1.15.4',          
          'lxml==4.3.0',
          'pytz==2018.7', 
          'pygeoj==1.0.0',
          'iso8601==0.1.12',
          'pyproj==1.9.5.1',
          'owslib==0.16.0',
          'urllib3==1.24.1',
          'pytest==4.0.2',
      ],
  classifiers=[
    'Development Status :: 3 - Alpha',      
    'Intended Audience :: Developers',      
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',   
    'Programming Language :: Python :: 3',      
  ],
)
