from setuptools import find_packages, setup

setup(
    name="politico-civic-campaign-tracker",
    version="0.4.4",
    description="",
    url="https://github.com/The-Politico/politico-civic-campaign-tracker",
    author="POLITICO interactive news",
    author_email="interactives@politico.com",
    license="MIT",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Framework :: Django",
        "Framework :: Django :: 2.0",
        "Intended Audience :: Developers",
        "Intended Audience :: Information Technology",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Topic :: Internet :: WWW/HTTP",
    ],
    keywords="",
    packages=find_packages(exclude=["docs", "tests", "example"]),
    include_package_data=True,
    install_requires=[
        "celery",
        "django-cors-headers",
        "django",
        "django-nested-admin",
        "djangorestframework",
        "dj-database-url",
        "politico-civic-entity",
        "politico-civic-geography",
        "politico-civic-government",
        "politico-civic-election",
        "politico-civic-biography",
        "politico-civic-campaign",
        "psycopg2",
        "requests",
        "python-twitter",
        "webpreview",
    ],
    extras_require={"test": ["pytest"]},
)
