
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-07T10:01:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a85b0fc47a20ec53bef95bd136efbc40e186cca0",
 "version": "V3.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
