
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-23T06:51:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a16174f66c88d953e5b29c7d497717d65195847",
 "version": "1.12.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
