
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-01T20:29:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c2339c18ca42e9afdf8aa4f83043891391c9a04",
 "version": "v2019.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
