# coding: utf-8

"""
    Nucleus API

    BETA version of the nucleus text analytics API. Example and documentation: https://github.com/SumUpAnalytics/nucleus-sdk  # noqa: E501

    OpenAPI spec version: v0.2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.user_model import UserModel  # noqa: E501
from nucleus_api.rest import ApiException


class TestUserModel(unittest.TestCase):
    """UserModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserModel(self):
        """Test UserModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.user_model.UserModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
