# http://travis-ci.org/#!/ashleysommer/stdeb
language: python
python:
    - "2.7_with_system_site_packages"
    - "3.4_with_system_site_packages"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-all-dev python3-all-dev debhelper python-setuptools python3-setuptools apt-file python-requests python3-requests
install:
    - which python3
    - which pip
    - pip --version
    - python3 -c "import sys; print(sys.version)"
    # Build a .deb file and then install it.
    - python3 setup.py --command-packages=stdeb3.command bdist_deb
    - for f in deb_dist/*.deb; do echo; echo $f; dpkg --contents $f; done
    - sudo dpkg -i deb_dist/*.deb
script:
    - sudo env "PATH=$PATH" bash -x ./test.sh
    - sudo env "PATH=$PATH" bash -x ./test-pypi-install.sh
    - sudo env "PATH=$PATH" bash -x ./test2and3.sh
