
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-05T17:56:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfb14d2401cd5a4e049a02f1063d753802c65219",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
