# Generated by Django 2.0.6 on 2018-10-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('campaigns', '0003_auto_20180926_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSupplierCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Campaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
