sudo: false
language: python
branches:
  except:
  - gh-page
  - "/release\\/v.*-pre/"
python:
- '2.7'
- '3.4'
- '3.6'
install:
- pip install tox-travis
script:
- tox
jobs:
  include:
  - stage: deploy
    if: branch = master
    python: 3.6
    install:
    - pip install tox-travis
    script: tox
    deploy:
      provider: pypi
      skip_existing: true
      user: nolte07
      password:
        secure: qs9anHkElr8f3+jH7gYBUMDzmyDCMHHVpv/nEe0gEIqPxDkVeqbgAAl6HnqWRp4FZfYUbZyGsSO4VMddgRvmCjX0F/3g1w/+FwES0dy0RL6pRyB4XWIIhEBLBlqFn4V/cCgYYx+IgG8I0l+5j8lhB6lyfek5kHlECZesMOkmRkmD1RZ0aHI+4f240AoOG+g2o6oqE0k2t94lqTUeOErG2ChuaP7s0WqEGQpA5tX4jwLtAgzxbnx+Jmu4WugtlTKzVhqPb3Qv+5nkayc6ezDECy5PkTVCcymhyXIvweEojQPjvYUeRVZaWj4O2O81ZPdFwjVbt0JoB8wwTavjwZ80EvHzFZy2Jxk/DcQO55Z2nfiPueUl8AC/QQ8aeQm/KciKA3rBG5vohlI2umwrsLxnqa7Qn/YkXAQAsasOAZOG6KXk11iAHt7BTR1S+LGK1JRbixWxcHHVXOV8VJO1tzeekL7t6rttTZAb7yNjElRLzFy22lahFb8E1VQEwz6OgKN6Qp4aiMnTFK9SZAoAz4T8wMtx+1LvCxxZHoLrBM0SQuutv43fC4tKIR5uh9tKF6NqvAyZzb7PPnJ/DJgwW4AgFAEIO5g/jdABhJwiMtv6J2KBo0PwTLkGBpO7yQQExi2WOn0r5zYzDvqPf3CvFEGB5NF3Dv5OtsjKsvq+hgIUcgc=
      on:
        distributions: sdist bdist_wheel
        repo: nolte/gitlab-bulkcheckout
        branch: notexists
  - stage: deploy pypidev
    if: branch = develop
    python: 3.6
    install:
    - pip install tox-travis
    script: tox
    deploy:
      provider: pypi
      user: nolte
      server: https://test.pypi.org/legacy/
      skip_existing: true
      password:
        secure: KxU9/+6DdwhMvt8yuppjtE/MKWJ26kRLCCP57UYSeq868MKrTtKNJE/jI53kiGyDgzmWbt4jd7pce/9NN2lBRvsEd2+4C1Bu5Ld70gdu+9pDCpYHn4iPODJHz0IyvCBU0Q/VLPrDFCOmuZmFoJ89Rlo79bh6DhDxttdLTFnf3qjNpF8dqwen89cJXXRrtockOe1ZdZwi9KWf+2w6gjE67ZG/svaJ2H7qFqJLiIXjncrmNf7ITZt87j9dnqyrvQr7yNFGN5HapThm3PL8OG1esfU0sT7hXFMqK9Yanl8jpKYybrMgHrLoN7JrZ2oK8SSWr5nYysm01sIp6GczblTjL5QW1zzlBTUcVGCLzZLO8ZEHGvaOI7yW+TSEhYaOhEd0BH6nij6KTnspFK0F7yzJ0gNfOO4k2YQzAIAqynzQv6leeabq4/Wb42ykSYSB237KEzlssWBeezkmynVthS+ASVOKOSmU16/qN99+k7Ee9TA0bp3l6pMRVazd/T2GVBiQ5GZj0fZhiSNy24c2aGS3VAo+3mYUt9a8x/ZQY7toGuFsfvb9PTXN6/QGRdiTNjeTODuHx0jq1+R2nSwKARbfa27dRUCtQSbuZQFRQz4+pmqLETtjUJPJr0s+srAe5FdSC/wZ+aBTwzDFVKH5msU0xMizfvK/NOkj8QdeOehhKkQ=
      on:
        distributions: sdist bdist_wheel
        repo: nolte/gitlab-bulkcheckout
        branch: notexists
