
# parsetab_string.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ppstringCLOSEBR COLON EXPOP GATE INSTRMT INTEGER LPAREN MULTOP NOP OPENBR POVM PREP REFLBL RPAREN STRINGINDstrref  : STRINGIND REFLBLslcref : strref OPENBR INTEGER COLON INTEGER CLOSEBRslcref : strreflayerable : GATE\n                     | INSTRMT layer : layerablelayer : layer layerablelayer : layer MULTOP layerableexpable : LPAREN string RPARENexpable : OPENBR layer CLOSEBRexpable : GATE\n                   | INSTRMT\n                   | NOP expable : slcrefexpdstr : expable EXPOP INTEGERexpdstr : expablestring : expdstrstring : string expdstrstring : string MULTOP expdstrpstring : stringpstring : PREP stringppstring : pstringppstring : pstring POVM'
    
_lr_action_items = {'PREP':([0,],[4,]),'LPAREN':([0,3,4,5,6,7,9,10,11,12,13,16,17,18,20,26,27,28,29,30,37,],[7,7,7,-17,-16,7,-11,-12,-13,-14,-3,-18,7,7,7,-1,-19,-15,-9,-10,-2,]),'OPENBR':([0,3,4,5,6,7,9,10,11,12,13,16,17,18,20,26,27,28,29,30,37,],[8,8,8,-17,-16,8,-11,-12,-13,-14,25,-18,8,8,8,-1,-19,-15,-9,-10,-2,]),'GATE':([0,3,4,5,6,7,8,9,10,11,12,13,16,17,18,20,21,22,23,24,26,27,28,29,30,31,32,34,37,],[9,9,9,-17,-16,9,23,-11,-12,-13,-14,-3,-18,9,9,9,23,-6,-4,-5,-1,-19,-15,-9,-10,-7,23,-8,-2,]),'INSTRMT':([0,3,4,5,6,7,8,9,10,11,12,13,16,17,18,20,21,22,23,24,26,27,28,29,30,31,32,34,37,],[10,10,10,-17,-16,10,24,-11,-12,-13,-14,-3,-18,10,10,10,24,-6,-4,-5,-1,-19,-15,-9,-10,-7,24,-8,-2,]),'NOP':([0,3,4,5,6,7,9,10,11,12,13,16,17,18,20,26,27,28,29,30,37,],[11,11,11,-17,-16,11,-11,-12,-13,-14,-3,-18,11,11,11,-1,-19,-15,-9,-10,-2,]),'STRINGIND':([0,3,4,5,6,7,9,10,11,12,13,16,17,18,20,26,27,28,29,30,37,],[14,14,14,-17,-16,14,-11,-12,-13,-14,-3,-18,14,14,14,-1,-19,-15,-9,-10,-2,]),'$end':([1,2,3,5,6,9,10,11,12,13,15,16,18,26,27,28,29,30,37,],[0,-22,-20,-17,-16,-11,-12,-13,-14,-3,-23,-18,-21,-1,-19,-15,-9,-10,-2,]),'POVM':([2,3,5,6,9,10,11,12,13,16,18,26,27,28,29,30,37,],[15,-20,-17,-16,-11,-12,-13,-14,-3,-18,-21,-1,-19,-15,-9,-10,-2,]),'MULTOP':([3,5,6,9,10,11,12,13,16,18,20,21,22,23,24,26,27,28,29,30,31,34,37,],[17,-17,-16,-11,-12,-13,-14,-3,-18,17,17,32,-6,-4,-5,-1,-19,-15,-9,-10,-7,-8,-2,]),'RPAREN':([5,6,9,10,11,12,13,16,20,26,27,28,29,30,37,],[-17,-16,-11,-12,-13,-14,-3,-18,29,-1,-19,-15,-9,-10,-2,]),'EXPOP':([6,9,10,11,12,13,26,29,30,37,],[19,-11,-12,-13,-14,-3,-1,-9,-10,-2,]),'REFLBL':([14,],[26,]),'INTEGER':([19,25,35,],[28,33,36,]),'CLOSEBR':([21,22,23,24,31,34,36,],[30,-6,-4,-5,-7,-8,37,]),'COLON':([33,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ppstring':([0,],[1,]),'pstring':([0,],[2,]),'string':([0,4,7,],[3,18,20,]),'expdstr':([0,3,4,7,17,18,20,],[5,16,5,5,27,16,16,]),'expable':([0,3,4,7,17,18,20,],[6,6,6,6,6,6,6,]),'slcref':([0,3,4,7,17,18,20,],[12,12,12,12,12,12,12,]),'strref':([0,3,4,7,17,18,20,],[13,13,13,13,13,13,13,]),'layer':([8,],[21,]),'layerable':([8,21,32,],[22,31,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ppstring","S'",1,None,None,None),
  ('strref -> STRINGIND REFLBL','strref',2,'p_strref','circuitparser.py',165),
  ('slcref -> strref OPENBR INTEGER COLON INTEGER CLOSEBR','slcref',6,'p_slcref_slice','circuitparser.py',172),
  ('slcref -> strref','slcref',1,'p_slcref','circuitparser.py',178),
  ('layerable -> GATE','layerable',1,'p_layerable','circuitparser.py',183),
  ('layerable -> INSTRMT','layerable',1,'p_layerable','circuitparser.py',184),
  ('layer -> layerable','layer',1,'p_layer_layerable','circuitparser.py',189),
  ('layer -> layer layerable','layer',2,'p_layer_str','circuitparser.py',194),
  ('layer -> layer MULTOP layerable','layer',3,'p_layer','circuitparser.py',199),
  ('expable -> LPAREN string RPAREN','expable',3,'p_expable_paren','circuitparser.py',204),
  ('expable -> OPENBR layer CLOSEBR','expable',3,'p_expable_layer','circuitparser.py',209),
  ('expable -> GATE','expable',1,'p_expable_single','circuitparser.py',215),
  ('expable -> INSTRMT','expable',1,'p_expable_single','circuitparser.py',216),
  ('expable -> NOP','expable',1,'p_expable_single','circuitparser.py',217),
  ('expable -> slcref','expable',1,'p_expable','circuitparser.py',222),
  ('expdstr -> expable EXPOP INTEGER','expdstr',3,'p_expdstr_expop','circuitparser.py',227),
  ('expdstr -> expable','expdstr',1,'p_expdstr','circuitparser.py',232),
  ('string -> expdstr','string',1,'p_string_expdstr','circuitparser.py',237),
  ('string -> string expdstr','string',2,'p_string_str','circuitparser.py',242),
  ('string -> string MULTOP expdstr','string',3,'p_string','circuitparser.py',247),
  ('pstring -> string','pstring',1,'p_pstring','circuitparser.py',252),
  ('pstring -> PREP string','pstring',2,'p_pstring_prep','circuitparser.py',257),
  ('ppstring -> pstring','ppstring',1,'p_ppstring','circuitparser.py',262),
  ('ppstring -> pstring POVM','ppstring',2,'p_ppstring_povm','circuitparser.py',267),
]
