language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
script:
  - "pycodestyle csh_ldap"
  - "pylint csh_ldap"
