language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - python setup.py install
  - pip install coveralls codecov

script:
  - coverage run --source=mddatasetbuilder setup.py test
  - coverage combine

after_success:
  - coveralls
  - codecov
