# Generated by Django 2.0.6 on 2018-08-18 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ACCOUNT_USER_PROXY_MODEL),
        ('survey', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.ACCOUNT_USER_PROXY_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='in_response_of',
            field=models.ManyToManyField(blank=True, related_name='child_questions', to='survey.AnswerChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='in_response_of_question',
            field=models.ManyToManyField(blank=True, related_name='next_questions', to='survey.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='survey.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('question', 'contact')},
        ),
        migrations.AddField(
            model_name='mcqanswer',
            name='answer_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='survey.AnswerChoice'),
        ),
        migrations.AlterUniqueTogether(
            name='answerchoice',
            unique_together={('question', 'code')},
        ),
    ]
