# Generated by Django 2.0.6 on 2018-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180818_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='in_response_of_question',
            field=models.ManyToManyField(blank=True, help_text='Used for text based questions', related_name='next_questions', to='survey.Question'),
        ),
    ]
