# Generated by Django 2.0.6 on 2019-01-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-order', '-created')},
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='should_halt',
            field=models.BooleanField(default=False),
        ),
    ]
