language: python
sudo: required

python:
  - "2.6"
  - "2.7" 
  - "3.3"
  - "3.4" 
  - "3.5"
  - "3.6"
  - "3.6-dev"  
  - "3.7-dev"  
  - "nightly"

matrix:
  fast_finish: true

cache:
    apt: true
 
install:
  - sudo bash ./travis/install_cuda.sh
  - pip install --upgrade pip
  - pip install --ignore-installed setuptools
  - pip install --ignore-installed wheel
  - pip install --ignore-installed pytest-cov
  - pip install --ignore-installed pytest
  - pip install -e .

script:
  - python -c "import farneback3d"
  - pytest # or py.test for Python versions 3.5 and below

os:
  - linux
  # - osx

# addons:
#   apt:
#     packages:
