# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
