# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0002_totp_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
