
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-07T11:49:06-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b16f8aa8a6daf23656f3c38541649432dc89ab30",
 "version": "v0.4.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
