
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "fa39c6c91c3e670d53f0b6fc9f3080cf8bf11438",
 "version": "0.10.4.b3591"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
