pt_br = {" abs ": " abraços ",
  " agr ": " agora ",
  " amg ": " amigo ",
  " bb ": " bebê ",
  " bj ": " beijo ",
  " bjs ": " beijos ",
  " blz ": " beleza ",
  " bpn ": " bom para nós ",
  " brb ": " volto já ",
  " clr ": " caralho ",
  " clrh ": " caralho ",
  " cmg ": " comigo ",
  " cm ": " com ",
  " ctz ": " certeza ",
  " c* ": " cu ",
  " cvs ": " conversa ",
  " d+ ": " demais ",
  " dlc ": " delícia ",
  " dlç ": " delícia ",
  " dm ": " mensagem privada ",
  " dmr ": " demorou ",
  " dnv ": " de novo ",
  " dms ": " demais ",
  " doq ": " do que ",
  " dps ": " depois ",
  " duma ": " de uma ",
  " erridê ": " rodado ",
  " erride ": " rodado ",
  " euem ": " eu hein ",
  " fdp ": " filho da puta ",
  " fdpta ": " filho da puta ",
  " glr ": " galera ",
  " gnt ": " gente ",
  " hj ": " hoje ",
  " ja ": " já ",
  " k ": " risos ",
  " krai ": " caralho ",
  " kg ": " quilo ",
  " kgs ": " quilos ",
  " kk ": " risos ",
  " l1xo ": " lixo ",
  " lol ": " risos ",
  " miga ": " amiga ",
  " migo ": " amigo ",
  " mlc ": " maluco ",
  " mlk ": " moleque ",
  " mlks ": " moleques ",
  " mnh ": " minha ",
  " mp ": " ministério público ",
  " msm ": " mesmo ",
  " mta ": " muita ",
  " muleke ": " moleque ",
  " mulekes ": " moleques ",
  " nº ": " número ",
  " n° ": " número ",
  " n ": " não ",
  " ñ ": " não ",
  " ng ": " ninguém ",
  " np ": " sem problemas ",
  " ngm ": " ninguém ",
  " obg ": " obrigado ",
  " omg ": " meu deus ",
  " oq ": " o que ",
  " pfv ": " por favor ",
  " pls ": " por favor ",
  " plmns ": " pelo menos ",
  " pdc ": " pode crer ",
  " ppk ": " pepeca ",
  " pprt ": " papo reto ",
  " pq ": " porque ",
  " pqp ": " puta que pariu ",
  " pra ": " para ",
  " pro ": " para o ",
  " q ": " que ",
  " qd ": " quando ",
  " qdo ": " quando ",
  " qndo ": " quando ",
  " rd ": " rodado ",
  " rs ": " risos ",
  " sdd ": " saudade ",
  " sdds ": " saudades ",
  " sfd ": " safado ",
  " slc ": " você é louco ",
  " smdd ": " sem maldade ",
  " so ": " só ",
  " smp ": " sempre ",
  " sqn ": " só que não ",
  " sr ": " senhor ",
  " tá ": " está ",
  " ta ": " está ",
  " tava ": " estava ",
  " tb ": " também ",
  " tbm ": " também ",
  " td ": " tudo ",
  " tdb ": " tudo bom ",
  " tds ": " todos ",
  " tlg ": " está ligado ",
  " tmj ": " estamos juntos ",
  " tnc ": " tomar no cu ",
  " tô ": " estou ",
  " to ": " estou ",
  " tomannk ": " tomar no cu ",
  " tqr ": " tem que respeitar ",
  " v4g4bund0 ": " vagabundo ",
  " vdb ": " vai dar bom ",
  " vdd ": " verdade ",
  " vei ": " velho ",
  " vc ": " você ",
  " vcs ": " vocês ",
  " vrdd ": " verdade ",
  " vsf ": " vá se foder ",
  " wpp ": " whatsapp "}

en = {" i'm ": " I am ",
 " i'm'a ": " I am about to ",
 " i'm'o ": " I am going to ",
 " ive ": " I have ",
 " he's ": " he is ",
 " she's ": " she is ",
 " that's ": " that is ",
 " what's ": " what is ",
 " where's ": " where is ",
 " haven't ": " have not ",
 " mustn't've ": " must not have ",
 " shouldn't've ": " should not have ",
 " shouldn't ": " should not ",
 " ur ": " you are ",
 " somebody's ": " somebody is ",
 " someone's ": " someone is ",
 " something's ": " something is ",
 " that's ": " that is ",
 " 'tis ": " it is ",
 " 'twas ": " it was ",
 " wasn't ": " was not ",
 " we'd've ": " we would have ",
 " weren't ": " were not ",
 " when's ": " when is ",
 " who's ": " who is ",
 " there's ": " there is ",
 " why's ": " why is ",
 " let's ": " let us ",
 " how'd ": " how did ",
 " needn't ": " need not ",
 " ne'er ": " never ",
 " o'clock ": " of the clock ",
 " o'er ": " over ",
 " o'l ": " old ",
 " y'all ": " you all ",
 " shan't ": " shall not ",
 "\'ll": " will",
 "\'d\'ve": " would have",
 "\'ve": " have",
 "\'re": " are",
 "\'d": " would",
 " won't ": " will not ",
 " mayn't ": " may not ",
 " mightn't ": " might not ",
 " mustn't ": " must not ",
 " aren't ": " are not ",
 " isn't ": " is not ",
 " wouldn't ": " would not ",
 " can't ": " can not ",
 " cannot ": " can not ",
 " don't ": " do not ",
 " didn't ": " did not ",
 " doesn't ": " does not ",
 " it's ": " it is ",
 " weren't ": " were not ",
 " okay ": " ok ",
 " c'mon ": " come on ",
 "in'": " ing",
 " everyone's ": " everyone is ",
 "\'s": " s",
 " ain't ": " am not ",
 " amn't ": " am not ",
 " cain't ": " can not ",
 " 'cause ": " because ",
 " could've ": " could have ",
 " couldn't've ": " could not have ",
 " daren't ": " dare not ",
 " daresn't ": " dare not ",
 " e'er ": " ever ",
 " finna ": " fixing to ",
 " gimme ": " give me ",
 " gonna ": " going to ",
 " gon't ": " go not ",
 " gotta ": " got to ",
 " hadn't ": " had not ",
 " hasn't ": " has not "}

fr = {" c'est ": " ce est ",
 "d'": "de ",
 "j'": "je ",
 "s'": "se ",
 "qu'": "se ",
 "t'": "te "}