
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d5c57536babf6a23568dae22067208cb04d5a906",
 "version": "1.1.0.post.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
