[tool.poetry]
name = "dophon_manager"
version = "0.1.5r2"
description = "base manager for dophon framwork"
authors = ["CallMeE <ealohu@163.com>"]

[tool.poetry.dependencies]
python = "*"
toml = "*"
poetry = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.6"

[tool.poetry.scripts]
dophon_manager = "dophon_manager:main"
dophon-manager = "dophon_manager:main"
dophon = "dophon_manager:main"