
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-09T08:16:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "92474fffb42eadf707bc89c6d5a95e62b1737fd9",
 "version": "0.19.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
