language: python
stages:
  - lint
  - test
  - deploy
python:
  - "3.5"
  - "3.6"
  - "pypy3"
stage: test
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -r requirements-pip.txt
  - pip install -r requirements-test.txt
  - pip install --editable .
script:
  - pytest
jobs:
  include:
    - stage: lint
      python: 3.6
      install:
        - pip install -r requirements-pip.txt
        - pip install -r requirements-lint.txt
        - pip install --editable .
      script:
        - pylint pyppyn
        - pylint tests/*py
        - flake8
    - stage: test
      python: 3.7
      dist: xenial
    - stage: test
      os: windows
      language: sh
      python: 3.7
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      install:
        - python -m pip install -r requirements-pip.txt
        - python -m pip install -r requirements-test.txt
        - pip install --editable .
    - stage: test
      os: osx
      osx_image: xcode10.1
      language: sh
      python: 3.7
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - python3 -m pip install virtualenv
        - virtualenv $HOME/venv -p python3
        - source $HOME/venv/bin/activate
      before_cache:
        - brew cleanup
        - rm -f $HOME/.cache/pip/log/debug.log
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew/Library/Homebrew
          - /usr/local/Homebrew/Library/Taps
          - $HOME/.cache/pip
    - stage: deploy
      if: branch = dev
      python: 3.6
      install:
        - echo "Install"
      script:
        - sed -i -E "s/^(__version__ = \")(.*)\"/\1\2.$TRAVIS_BUILD_NUMBER\"/" $TRAVIS_BUILD_DIR/pyppyn/__init__.py
      deploy:
        - provider: pypi
          server: https://test.pypi.org/legacy/
          distributions: sdist bdist_wheel
          user: YakDriver
          password:
            secure: Ll07zP0rCGNtI60s3UFpYx9DRqoHMdKVEaGN7NnoFbPJtc+0wi4NE8ZlQXDCvdndDowiolJD5l0n/kO1XM7RSkaYpkSq7uHkOKnwvGPfVD9jt7aHkMT0hxij42v0+mbp/gxJZG0K+oouq34O6CgGzR9OOM8/6Z9xkMp72m0ULkIQ6SJyYPZ95zFeHumBLTRUWYhw/6jQNsTmyVwB1gSiB12dj2PkrlkZfXuZpy+QgwO2lmcl/b5jvWk8gPv1DxggV4FmaaXXlaJkV3+LSpIs0aiXX1vmS2Z+UXqJ2F9TY9d57b/Rk2bz7E5biVlJRSkLYyRteZUjzmeENZi20nX5t8DKB0EhJ5G6toEphTIY0SLLpbCWtmi5e/wv6FzZPvb86t9IJgp8kEZKHukofo4MwysXnt1fUGyqHpZeK8cGx68+QKisGsvrAkDqWrzeUR6IBS50hQbcOua2uVFgBui3jh3+TuTEiSNtED4DucEIi2RaVJBHGPiFM+ZV7hy3DSB6gGfLGmsC9NmUsZrJ5jMJXmKsCmOuttz7YszdeGbNLcv7lBlvDU4tA+6kWPXG9Wj4t326GnSvuHS7q5684Cv6cq/u4iI7bqS0RoQ8QbsRqANxWoBeo3X0AWdi6xsz/83ljMzROLTxV75BCgPXUeIL9iTY26owGw2hE6LDRkUitXI=
          skip_cleanup: true
          skip_upload_docs: true
          on:
            branch: dev
    - stage: deploy
      if: branch = master
      python: 3.6
      install:
        - echo "Install"
      script:
        - export RELEASE_VERSION=$(grep "__version__" $TRAVIS_BUILD_DIR/pyppyn/__init__.py | sed 's/__version__ = //' | sed 's/"//g')
        - export RELEASE_BODY="* [pyppyn v$RELEASE_VERSION CHANGELOG](https://github.com/YakDriver/pyppyn/blob/$RELEASE_VERSION/CHANGELOG.rst)"
      deploy:
        - provider: releases
          name: $RELEASE_VERSION
          tag_name: $RELEASE_VERSION
          target_commitish: $TRAVIS_COMMIT
          body: $RELEASE_BODY
          draft: false
          skip_cleanup: true
          api_key:
            secure: bk3oSSuNgpAFlEY9lyvPL/4eJoO0eUVz8Yh4gciOK+YFW8vCpH6c33psKd50QAxZi5sH2DhGN/ZfMwpZsX6x1jFDP7A4eRNh5hjAKaJmgLHigEzvp8rLgzQTJKafT/ay3HQclQyTTVT6GqO2b39pXHVttfY7XzmfQkwR9j9r+hfA/ktyl/1Mka32lPJokakU20sTvARr/pdeq0l5m2EJjJM5YIUuzjbd9D3t52va87eDzfOw64SPy1BdM0ZYaM2iZloFQg+gyGYLP0DX2qN99yKT9WyfVbaxrUcIY1kgMoWC9W7p/hyfU0qtHnvEX8W5sE7l4nfIfWOY3oclYUwV8wIPDqaB7tTldBgNWb5c1pGa3VnfFhzaToD7V7UYj7M9IDCoeBJK07kaHN2a3iYgETv/IkjzybXq42hSbomkv+iSD7iCvM5ewFEVJ6n0WQp9Q/uNrbpDwdMQ5ONIILP2KYmtNCFRIHkIBwYR2ku9UMrRnsyjOXCx49EkibwXkvrv4TAH9L8f7K6WeTxIpwGkQ+NrzX3FzWb9beYRa96yKkbfW3Hm196SyPSeE4qqd3ilaKixvtE1l8XqJt0QmdrGiyDKts17p5pVNulqyIuLrcOkXGk7JmzpOXkXpT9P88NacugBH/4DuM9Z/p+nm+pUtxjPDAxtAL2rgoufBjRlWNo=
          on:
            branch: master
    - stage: deploy
      if: tag is present
      python: 3.6
      install:
        - echo "Install"
      script:
        - echo "Script"
      deploy:
          - provider: pypi
            distributions: sdist bdist_wheel
            user: YakDriver
            password:
              secure: msxEPL7wdduLIN+T9xm58nsN2of/wqUU985oJUjsTx6AiUBJFBfLeo/xJ92ne93ZSnlJA29Pj2zi6DeW2o9hJ/WhPoicBUdpQCdTEfsKZGS2CXHVQLg8D5njJi32EWha9dV5PicwQwxN1olHtG1KrU5N/NljWWvMuK3UHy74BSnikxu8s7t9Tww5umlecd8rQGyARipdQGOUQDmJre5RMmFSldmnQ+TkO47uBMkhdvbnixoqM2sAyqeQ198G4nL35bx7zSGuhZjcdS8UgSz+QeAyx9wDiwqEb6GgR+zJMU934bLMtNgV0sfHYsvm6Pkg5HnCmpPieXBYjCtjeJNIeZVGsP4Speq/Q7nKoxx/Yl1/CtBCX5qEUzjcZo0YizA5ipeYzz1jios9XkDbignJAW5iy4M6MKVdSn5XOW0Qsg6CzEJJGyR+5lsVc3okU2MaRmXKA2PdldknEsgGjy5zc75jXjEfWRQsuM1Tp6dFN3898mjYjmJfFQK8z74sq7IJXQYHi00nmslgkWEJVgOqRydAn+vqy9ug3h6dqw+0BK7A/tg28HkCucG9/eMyqcZT2yYulKSxy7E5C55nmzajVhD5RqIM561dNsmq8mpuJpWlp8RIQKgb5WAPQ/52T/3T+R/tc2vGFc/Ra7dXHygrQHfFSbD/dl4nNQY8rMmWLek=
            skip_upload_docs: true
            on:
              tags: true
