
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d8ccfe19ae50e7ee8d1d9f81abe7c475fd616aaa",
 "version": "1.8.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
