# Generated by Django 2.0.6 on 2018-09-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ACCOUNT_USER_PROXY_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500, null=True)),
                ('content', models.TextField()),
                ('media', models.FileField(upload_to='social/%d%m%y/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('schedule_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCOUNT_USER_PROXY_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(1, 'Facebook Page'), (2, 'Facebook Group'), (3, 'Instagram'), (4, 'Twitter'), (5, 'LinkedIn')], null=True)),
                ('target_id', models.CharField(max_length=400, null=True)),
                ('target_link', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Post')),
            ],
        ),
    ]
