# Generated by Django 2.0.6 on 2018-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedto',
            name='target_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
