
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-10T19:47:13-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1e367792a530f33bd1914101e30702af7a9b6c4",
 "version": "0.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
