
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-21T17:03:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d71057df6cd7db48cfcbfacc21e77b4b79176afa",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
