# Generated by Django 2.0.8 on 2018-12-09 22:00

from django.db import migrations, models
import django_paymentsos.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsOSNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', django_paymentsos.fields.JSONField(blank=True)),
                ('additional_details', django_paymentsos.fields.JSONField(blank=True)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('token_type', models.CharField(blank=True, max_length=100)),
                ('holder_name', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.CharField(blank=True, max_length=100)),
                ('last_4_digits', models.CharField(blank=True, max_length=100)),
                ('pass_luhn_validation', models.BooleanField(default=False)),
                ('fingerprint', models.CharField(blank=True, max_length=100)),
                ('bin_number', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('issuer', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=100)),
                ('method_created', models.CharField(blank=True, max_length=100)),
                ('billing_address', django_paymentsos.fields.JSONField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('result_description', models.CharField(blank=True, max_length=100)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('response_code', models.CharField(blank=True, max_length=100)),
                ('provider_description', models.CharField(blank=True, max_length=100)),
                ('raw_response', django_paymentsos.fields.JSONField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('flag', models.BooleanField(default=False)),
                ('flag_code', models.CharField(blank=True, choices=[('1001', 'Duplicated Webhook'), ('1002', 'Invalid Sign')], max_length=4)),
                ('flag_info', models.CharField(blank=True, max_length=100)),
                ('data_id', models.CharField(blank=True, max_length=100)),
                ('reconciliation_id', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('modified', models.CharField(blank=True, max_length=100)),
                ('notification_created', models.CharField(blank=True, max_length=100)),
                ('webhook_id', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('app_id', models.CharField(blank=True, max_length=100)),
                ('x_zooz_request_id', models.CharField(blank=True, max_length=100)),
                ('x_payments_os_env', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField()),
                ('raw', django_paymentsos.fields.JSONField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paymentsos_notification',
            },
        ),
    ]
