# Generated by Django 2.0.8 on 2018-12-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_paymentsos', '0003_auto_20181216_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsosnotification',
            options={'verbose_name': 'PaymentsOS Notification', 'verbose_name_plural': 'PaymentsOS Notifications'},
        ),
    ]
