__title__ = "sve"
__description__ = "Service vulnerability enumeration tool"
__version__ = "0.3.2"
__author__ = "Jason Phan"
__author_email__ = "xorblonded@gmail.com"
__url__ = "https://github.com/bl0nd/sve"
__license__ = "MIT"
