# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from optuna_firestore_proto import study_pb2 as optuna__firestore__proto_dot_study__pb2


class StudyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateNewStudyId = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/CreateNewStudyId',
        request_serializer=optuna__firestore__proto_dot_study__pb2.CreateNewStudyIdRequest.SerializeToString,
        response_deserializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.FromString,
        )
    self.GetStudyFromId = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/GetStudyFromId',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
        response_deserializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.FromString,
        )
    self.GetStudyFromName = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/GetStudyFromName',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.FromString,
        )
    self.SetStudyUserAttr = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/SetStudyUserAttr',
        request_serializer=optuna__firestore__proto_dot_study__pb2.SetStudyUserAttrRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SetStudySystemAttr = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/SetStudySystemAttr',
        request_serializer=optuna__firestore__proto_dot_study__pb2.SetStudySystemAttrRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SetStudyDirection = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/SetStudyDirection',
        request_serializer=optuna__firestore__proto_dot_study__pb2.SetStudyDirectionRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetAllStudySummaries = channel.unary_unary(
        '/optuna_firestore_proto.StudyService/GetAllStudySummaries',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=optuna__firestore__proto_dot_study__pb2.GetAllStudySummariesResponse.FromString,
        )


class StudyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateNewStudyId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStudyFromId(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStudyFromName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetStudyUserAttr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetStudySystemAttr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetStudyDirection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllStudySummaries(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StudyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateNewStudyId': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNewStudyId,
          request_deserializer=optuna__firestore__proto_dot_study__pb2.CreateNewStudyIdRequest.FromString,
          response_serializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.SerializeToString,
      ),
      'GetStudyFromId': grpc.unary_unary_rpc_method_handler(
          servicer.GetStudyFromId,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
          response_serializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.SerializeToString,
      ),
      'GetStudyFromName': grpc.unary_unary_rpc_method_handler(
          servicer.GetStudyFromName,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=optuna__firestore__proto_dot_study__pb2.StudyMsg.SerializeToString,
      ),
      'SetStudyUserAttr': grpc.unary_unary_rpc_method_handler(
          servicer.SetStudyUserAttr,
          request_deserializer=optuna__firestore__proto_dot_study__pb2.SetStudyUserAttrRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SetStudySystemAttr': grpc.unary_unary_rpc_method_handler(
          servicer.SetStudySystemAttr,
          request_deserializer=optuna__firestore__proto_dot_study__pb2.SetStudySystemAttrRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SetStudyDirection': grpc.unary_unary_rpc_method_handler(
          servicer.SetStudyDirection,
          request_deserializer=optuna__firestore__proto_dot_study__pb2.SetStudyDirectionRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetAllStudySummaries': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllStudySummaries,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=optuna__firestore__proto_dot_study__pb2.GetAllStudySummariesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'optuna_firestore_proto.StudyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
