
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-30T16:39:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ff044fcc54e3325a1705c0202001d7dad3b6ae66",
 "version": "v1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
