# Generated by Django 2.0.6 on 2019-01-28 03:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181206_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cell_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('CS', 'Card Scan'), ('DBC', 'Digital Business Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='google_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='digital/cards'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(blank=True, choices=[('M', 'mobile'), ('W', 'Website')], default='W', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='text_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='blog',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='foursquare',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='google_plus',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='meetup',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='pinterest',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='skype',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='snapchat_user',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='whatsup_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsocialprofile',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactsocialprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
