# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\plot_widget.ui',
# licensing of 'D:\repos\Jetperch\pyjoulescope_ui\joulescope_ui\plot_widget.ui' applies.
#
# Created: Sun Jan 27 17:51:08 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PlotDockWidget(object):
    def setupUi(self, PlotDockWidget):
        PlotDockWidget.setObjectName("PlotDockWidget")
        PlotDockWidget.resize(867, 506)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.topWidget.setObjectName("topWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectXButton = QtWidgets.QPushButton(self.topWidget)
        self.selectXButton.setCheckable(True)
        self.selectXButton.setObjectName("selectXButton")
        self.horizontalLayout.addWidget(self.selectXButton)
        self.selectYButton = QtWidgets.QPushButton(self.topWidget)
        self.selectYButton.setMinimumSize(QtCore.QSize(66, 0))
        self.selectYButton.setCheckable(True)
        self.selectYButton.setObjectName("selectYButton")
        self.horizontalLayout.addWidget(self.selectYButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.topWidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.meanLabel = QtWidgets.QLabel(self.widget)
        self.meanLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.meanLabel.setObjectName("meanLabel")
        self.gridLayout.addWidget(self.meanLabel, 0, 5, 1, 1)
        self.maxLabel = QtWidgets.QLabel(self.widget)
        self.maxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout.addWidget(self.maxLabel, 0, 14, 1, 1)
        self.minLabel = QtWidgets.QLabel(self.widget)
        self.minLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout.addWidget(self.minLabel, 0, 12, 1, 1)
        self.p2pValue = QtWidgets.QLabel(self.widget)
        self.p2pValue.setObjectName("p2pValue")
        self.gridLayout.addWidget(self.p2pValue, 0, 11, 1, 1)
        self.stdValue = QtWidgets.QLabel(self.widget)
        self.stdValue.setObjectName("stdValue")
        self.gridLayout.addWidget(self.stdValue, 0, 9, 1, 1)
        self.maxValue = QtWidgets.QLabel(self.widget)
        self.maxValue.setObjectName("maxValue")
        self.gridLayout.addWidget(self.maxValue, 0, 16, 1, 1)
        self.p2pLabel = QtWidgets.QLabel(self.widget)
        self.p2pLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2pLabel.setObjectName("p2pLabel")
        self.gridLayout.addWidget(self.p2pLabel, 0, 10, 1, 1)
        self.minValue = QtWidgets.QLabel(self.widget)
        self.minValue.setObjectName("minValue")
        self.gridLayout.addWidget(self.minValue, 0, 13, 1, 1)
        self.stdLabel = QtWidgets.QLabel(self.widget)
        self.stdLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stdLabel.setObjectName("stdLabel")
        self.gridLayout.addWidget(self.stdLabel, 0, 8, 1, 1)
        self.meanValue = QtWidgets.QLabel(self.widget)
        self.meanValue.setObjectName("meanValue")
        self.gridLayout.addWidget(self.meanValue, 0, 6, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout.addWidget(self.topWidget)
        self.mainWidget = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setObjectName("mainWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout.addWidget(self.mainWidget)
        PlotDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(PlotDockWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotDockWidget)

    def retranslateUi(self, PlotDockWidget):
        PlotDockWidget.setWindowTitle(QtWidgets.QApplication.translate("PlotDockWidget", "Plot", None, -1))
        self.selectXButton.setText(QtWidgets.QApplication.translate("PlotDockWidget", "X", None, -1))
        self.selectYButton.setText(QtWidgets.QApplication.translate("PlotDockWidget", "Y", None, -1))
        self.meanLabel.setText(QtWidgets.QApplication.translate("PlotDockWidget", "    μ=", None, -1))
        self.maxLabel.setText(QtWidgets.QApplication.translate("PlotDockWidget", "    max= ", None, -1))
        self.minLabel.setText(QtWidgets.QApplication.translate("PlotDockWidget", "    min= ", None, -1))
        self.p2pValue.setText(QtWidgets.QApplication.translate("PlotDockWidget", "0", None, -1))
        self.stdValue.setText(QtWidgets.QApplication.translate("PlotDockWidget", "0", None, -1))
        self.maxValue.setText(QtWidgets.QApplication.translate("PlotDockWidget", "0", None, -1))
        self.p2pLabel.setText(QtWidgets.QApplication.translate("PlotDockWidget", "    p2p= ", None, -1))
        self.minValue.setText(QtWidgets.QApplication.translate("PlotDockWidget", "0", None, -1))
        self.stdLabel.setText(QtWidgets.QApplication.translate("PlotDockWidget", "    σ=", None, -1))
        self.meanValue.setText(QtWidgets.QApplication.translate("PlotDockWidget", "0", None, -1))

