
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-04T18:21:16-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcd5257f4849aabb1c21ff469b4444e702e8351f",
 "version": "0.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
