
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-05T17:15:22-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5126cf4522040c59bd4cd2408c861f13736cf65f",
 "version": "v0.4.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
