
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "301122413e59c00528d5e5eb1609c255cc187538",
 "version": "0.1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
