# Generated by Django 2.0.6 on 2018-08-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.ACCOUNT_USER_PROXY_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=16)),
                ('friendly_name', models.CharField(max_length=16)),
                ('notes', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers',
                                           to=settings.ACCOUNT_USER_PROXY_MODEL)),
            ],
        ),
    ]
