[tool.poetry]
name = "all_purpose_set"
version = "0.1.1"
description = "A set that works with both hashable and non-hashable elements"
authors = ["Philip Olson <philip.olson@pm.me>"]
readme = "README.md"
repository = "https://github.com/olsonpm/py_all-purpose-set"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
ordered_set = "^3.1"
wrapt = "^1.10"
tedent = "^0.1.1"

[tool.poetry.dev-dependencies]
simple_chalk = "^0.1.0"
is_git_repo_clean = "^0.3.4"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
