# Generated by Django 2.1.3 on 2018-11-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0007_electionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='election.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='RankingTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('short_label', models.CharField(max_length=30)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='tracker.RankingTier'),
        ),
    ]
