# Generated by Django 2.1.3 on 2018-11-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_electionevent'),
        ('campaign', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField()),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='content', to='campaign.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRunRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_ratings', to='election.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateWinRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='win_ratings', to='election.Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='tier',
        ),
        migrations.RenameModel(
            old_name='RankingTier',
            new_name='CandidateRatingCategory',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.AddField(
            model_name='candidatewinrating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='win_ratings', to='tracker.CandidateRatingCategory'),
        ),
        migrations.AddField(
            model_name='candidaterunrating',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_ratings', to='tracker.CandidateRatingCategory'),
        ),
    ]
