# Generated by Django 2.1.4 on 2018-12-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='election.Candidate'),
        ),
    ]
