# Generated by Django 2.1.4 on 2018-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20181207_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='byline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
