# Generated by Django 2.1.4 on 2018-12-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20181213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateranking',
            name='candidate',
            field=models.ForeignKey(limit_choices_to={'race__cycle__slug': '2020', 'race__office__slug': 'president'}, on_delete=django.db.models.deletion.PROTECT, related_name='rankings', to='election.Candidate'),
        ),
    ]
