# Generated by Django 2.1.5 on 2019-01-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20181218_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidateranking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='candidateranking',
            name='date',
        ),
    ]
