[tool.poetry]
name = "dophon_mq"
version = "1.0.0r5"
description = "dophon mq module"
authors = ["CallMeE <ealohu@163.com>"]
license='Apache 2.0'
url='https://gitee.com/callmee/dophon-mq'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
python = "^3.6"
