- job:
    name: python-barbicanclient-dsvm
    parent: legacy-dsvm-base
    run: playbooks/python-barbicanclient-dsvm/run.yaml
    post-run: playbooks/python-barbicanclient-dsvm/post.yaml
    timeout: 4200
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstackclient-plugin-jobs
    check:
      jobs:
        - openstack-tox-lower-constraints
        - python-barbicanclient-dsvm
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - python-barbicanclient-dsvm
