sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- docker
- redis
cache: pip
install:
- pip install --upgrade pip setuptools wheel
script:
- docker-compose build
- docker-compose up --no-start
- docker-compose start postgres
- docker-compose run --rm server sh -c "/redash-stmo/bin/wait-for-it.sh postgres:5432 -- python manage.py database create_tables"
- docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests;"
- docker-compose run server tests
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  user: emtwo
  distributions: sdist bdist_wheel
  password:
    secure: t+gT1RLpn7k4yVD+uU4QRVXOssjh7kih6VAgpj/WPi/uWAEJ2CEj6SwXQhAKzuvtbGglkAiCL7wsWqUNFzmRmTRMnxZwrVESXpuqGjc44jBV/JHGbuFlzY+ycJl7xW3rt/JXydw4O50F/0IuIf+1M6VmosLd0HZw5Sny92DTZm7AHyJbS8vtJEFoewP2J4XmGT6h1Ldq0l/tXyGdzJWo3xKltxewwYnGuksyTOR9c4fmg6TiA1EVXNA6QdJGIZR8SbO0y6ZJ+Y1+RVYzmFSCDPku5SD8cQDGs3xcFu048DqEuWITP2wGmSfsHX9U1LqCkRDPFjNM2JGpOOiEx7mGe8Vyx72RPS4sfpKgkvLZxBFZWlqj8miPkaqPNCAgaOOeMw6fgOa28jGLkU/svFSQdv4RB1dFrrvwoDPBlNKvmzOtJX4Pc3vJ14rFa8KhxF3aBzdTGFQU7KoPhIOA5qRmZwbdHbdWN5NSODJOVcXkR0GBe86PcL6g9SHPM7pENOvVns/nXbmBtChuYRFJ5s8hCWLTiUKfHgqN6l4c8Tueg+0yrLzz+vzkj9e5s/FxxFpjuU9VNbes0uvZPEKc4lSAi6awZBmjfZhppnyhFEeYYfgacqIIt/cme4LpamyU3ck9zmJZnKC+/r4qVAaLRUWPfSAk9a+U/QAMSJeumiW0E0U=
  on:
    tags: true
    repo: mozilla/redash-stmo
    python: '3.5'
