[tool.poetry]
name = "dat-daemon-pyclient"
version = "0.1.0"
description = "a client for the dat-daemon"
authors = ["Rigel Kent <sendmemail@rigelk.eu>"]
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.7"
websockets = "^7.0"
asyncio = "^3.4"
grpcio-tools = "^1.18"
protobuf = "^3.6"
promise = "^2.2"

[tool.poetry.dev-dependencies]
pytest-asyncio = "^0.10.0"
pytest = "^4.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
