#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='lc3vm',
      version='1.0',
      description='Implementation of virtual machine for LC-3 assembly language in python',
      author='Paul Nameless',
      author_email='paul.nameless@icloud.com',
      url='https://github.com/paul-nameless',
      py_modules=['lc3vm'],
     )
