language: python
python:
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install -r requirements.txt
script: make travis
after_success: coveralls
notifications:
  email:
    - silpa-discuss@nongnu.org
