stages:
  - name: test
  - name: deploy-pip
    if: tag IS present
  - name: deploy-mkdocs
    if: tag IS present
  - name: deploy-release
    if: tag IS present

jobs:
  include:
    - stage: test
      name: "Tests"
      language: python
      python:
        - '3.5'
        - '3.6'
        - '3.7'
      dist: xenial
      sudo: true
      install:
        - pip install -r test-requirements.txt
        - pip install codecov
      script:
        - pytest --cov gitrack
      after_success:
        - codecov
    - stage: deploy-pip
      name: "Publish to PyPi"
      language: python
      python: '3.6'
      dist: xenial
      sudo: true
      script:
        - pip install -r test-requirements.txt
      deploy:
        provider: pypi
        user: AuHau-deploy
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          tags: true
          repo: AuHau/giTrack
        password:
          secure: rHJUt4Qc4JSjRcydN8Yh7gIcqGrbZAwyP2VbKrQBcowMAOMVuQLDZ/KZvcfEl2X5tcDaIgH/IIJm1DYxOqDyguho8jvEMrjgqRPFNzgO21eBvwMT5UEsA7mNnZ85lKLaW2LufS9p21UUVJhFcMy5d4hMkSJpJkC9y5RC3Jl15jVFSynbS4nLf5p28fg2gPab17z/RAICA3Muax9dsTiTDrtZ/hYHxuKm8ifFbuuGptmdU7q9q/oBmlboipdfcHzXJabpr3e62ZNmuot4byaA4xsWK00vFqIXGO0vHdwtdSKBNC68vCaonDxqJ3FS5HeioqGU1Dq4NBdnHQMR/8r4Gcq6WhQ/TI3lVKKAHTx8VJjO8DM/UKrNH/FRtPMSlvx8FDZ4LcvIvmNiz2gAF8cnvyqJPNVYtjYnkngtlOdLvnUIjBHJBCk10yeBCvMXCo+RkwpDY0QxsaSXLyRSkVjngbt6lg7l/BYcY3ZBom5KDMcjxDURe8rDxaPc05oVOLT04uwppKVcrJwJSomK6gajXAZwHaQhXC5jwVR+G9r69BdWawrJ1/mN8Atav9EPsahS4D9EzSBEBRRK1vgWEryW5kYJfamrGsxDfIlOZKUdBz+h8pWEt9PhIfC3WKcvwXAE3PNtfdQaqtQTktIzGCUIUro6z5a3ojtgaxG4Xm+cLJg=
    - stage: deploy-mkdocs
      name: "Publish documentation"
      language: python
      python: '3.6'
      dist: xenial
      sudo: true
      install:
        - pip install -r test-requirements.txt
      script:
        - git config user.name "Adam Uhlir";
        - git config user.email "hello@adam-uhlir.me";
        - git remote add gh-token "https://${GH_TOKEN}@github.com/AuHau/giTrack.git";
        - git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
        - mkdocs gh-deploy -v --clean --remote-name gh-token;
    - stage: deploy-release
      name: "Build and publish PEX to draft release"
      language: python
      python: '3.7'
      dist: xenial
      sudo: true
      install:
        - pip install pex
      script:
        - pex --python=python3 -r requirements.txt -o ./build/gitrack.linux-x86_64 --platform linux-x86_64 --manylinux -e gitrack.main gitrack setuptools
        # - pex --python=python3 -r requirements.txt -o ./build/gitrack.macosx_x86_64 --platform macosx_10_12_x86_64 --platform macosx_10_13_x86_64 --platform macosx_10_14_x86_64 -e gitrack.main gitrack setuptools
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: ${GH_TOKEN}
        draft: true
        file:
          - ./build/gitrack.linux-x86_64
          - ./build/gitrack.macosx-x86_64
        on:
          tags: true
          repo: AuHau/giTrack