[tool.poetry]
name = "derivative"
version = "0.1.2"
description = ""
authors = ["Markus Quade <info@markusqua.de>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.16"
scipy = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
matplotlib = "^3.0"

[tool.black]
line-length = 111
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
