[tool.poetry]
name = "pretty_simple_namespace"
version = "0.1.0"
description = "A pretty printer for SimpleNamespace"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_pretty-simple-namespace"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
wrapt = "^1.10"
ordered_set = "^3.1"
all_purpose_dict = "^0.1.2"
all_purpose_set = "^0.1.4"
another_linked_list = "^0.1.0"

[tool.poetry.dev-dependencies]
simple_chalk = "^0.1.0"
case_conversion = "^2.1"
is_git_repo_clean = "^0.3.4"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
