# Generated by Django 2.0.6 on 2019-01-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190104_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='mode',
            field=models.CharField(choices=[('1', 'PAYPAL'), ('2', 'Credit Card')], default=2, max_length=255, verbose_name='Payment Source'),
        ),
    ]
