# Version file autogenerated by the build process
version = '0.6.0rc5'
build = '247'
vcs_info = 'Git SHA1 a7a6214f committed on 2019-02-06'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.6.0rc5"\nKSCONF_BUILD="247"\nKSCONF_VCS_INFO="Git SHA1 a7a6214f committed on 2019-02-06"')
