# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_campaign_keyword',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_campaign_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_session_medium',
            field=models.TextField(default='unkown'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_session_source',
            field=models.TextField(default='unknown'),
        ),
    ]
