
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-02T12:14:38-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "502f7d7313068b1006f3665dba4f3ae47164083b",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
