# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot_gui/forms/designer/frm_samples_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(851, 1064)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LBL_TITLE_MAIN = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE_MAIN.setObjectName("LBL_TITLE_MAIN")
        self.horizontalLayout_2.addWidget(self.LBL_TITLE_MAIN, 0, QtCore.Qt.AlignBottom)
        self.BTN_REFRESH = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_REFRESH.sizePolicy().hasHeightForWidth())
        self.BTN_REFRESH.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/groot/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_REFRESH.setIcon(icon)
        self.BTN_REFRESH.setAutoDefault(False)
        self.BTN_REFRESH.setObjectName("BTN_REFRESH")
        self.horizontalLayout_2.addWidget(self.BTN_REFRESH)
        self.BTN_HELP = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_HELP.sizePolicy().hasHeightForWidth())
        self.BTN_HELP.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/groot/help.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_HELP.setIcon(icon1)
        self.BTN_HELP.setAutoDefault(False)
        self.BTN_HELP.setObjectName("BTN_HELP")
        self.horizontalLayout_2.addWidget(self.BTN_HELP)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.LBL_HAS_DATA_WARNING = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBL_HAS_DATA_WARNING.sizePolicy().hasHeightForWidth())
        self.LBL_HAS_DATA_WARNING.setSizePolicy(sizePolicy)
        self.LBL_HAS_DATA_WARNING.setObjectName("LBL_HAS_DATA_WARNING")
        self.verticalLayout.addWidget(self.LBL_HAS_DATA_WARNING)
        self.LBL_TITLE_WORKSPACE = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE_WORKSPACE.setObjectName("LBL_TITLE_WORKSPACE")
        self.verticalLayout.addWidget(self.LBL_TITLE_WORKSPACE)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BTN_SHOW_WORKSPACE = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_WORKSPACE.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_WORKSPACE.setSizePolicy(sizePolicy)
        self.BTN_SHOW_WORKSPACE.setObjectName("BTN_SHOW_WORKSPACE")
        self.verticalLayout_2.addWidget(self.BTN_SHOW_WORKSPACE)
        self.FRA_WORKSPACE = QtWidgets.QFrame(Dialog)
        self.FRA_WORKSPACE.setMinimumSize(QtCore.QSize(0, 192))
        self.FRA_WORKSPACE.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FRA_WORKSPACE.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FRA_WORKSPACE.setObjectName("FRA_WORKSPACE")
        self.LAY_WORKSPACE = QtWidgets.QGridLayout(self.FRA_WORKSPACE)
        self.LAY_WORKSPACE.setObjectName("LAY_WORKSPACE")
        self.verticalLayout_2.addWidget(self.FRA_WORKSPACE)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TXT_WORKSPACE = QtWidgets.QLineEdit(Dialog)
        self.TXT_WORKSPACE.setObjectName("TXT_WORKSPACE")
        self.horizontalLayout.addWidget(self.TXT_WORKSPACE)
        self.BTN_NEW_WORKSPACE = QtWidgets.QPushButton(Dialog)
        self.BTN_NEW_WORKSPACE.setAutoDefault(False)
        self.BTN_NEW_WORKSPACE.setObjectName("BTN_NEW_WORKSPACE")
        self.horizontalLayout.addWidget(self.BTN_NEW_WORKSPACE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.LBL_TITLE_RECENT = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE_RECENT.setObjectName("LBL_TITLE_RECENT")
        self.verticalLayout.addWidget(self.LBL_TITLE_RECENT)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BTN_SHOW_RECENT = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_RECENT.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_RECENT.setSizePolicy(sizePolicy)
        self.BTN_SHOW_RECENT.setObjectName("BTN_SHOW_RECENT")
        self.verticalLayout_3.addWidget(self.BTN_SHOW_RECENT)
        self.FRA_RECENT = QtWidgets.QFrame(Dialog)
        self.FRA_RECENT.setMinimumSize(QtCore.QSize(0, 192))
        self.FRA_RECENT.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FRA_RECENT.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FRA_RECENT.setObjectName("FRA_RECENT")
        self.LAY_RECENT = QtWidgets.QGridLayout(self.FRA_RECENT)
        self.LAY_RECENT.setObjectName("LAY_RECENT")
        self.verticalLayout_3.addWidget(self.FRA_RECENT)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.LBL_TITLE_SAMPLE = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE_SAMPLE.setObjectName("LBL_TITLE_SAMPLE")
        self.verticalLayout.addWidget(self.LBL_TITLE_SAMPLE)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BTN_SHOW_SAMPLE = QtWidgets.QToolButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SHOW_SAMPLE.sizePolicy().hasHeightForWidth())
        self.BTN_SHOW_SAMPLE.setSizePolicy(sizePolicy)
        self.BTN_SHOW_SAMPLE.setObjectName("BTN_SHOW_SAMPLE")
        self.verticalLayout_4.addWidget(self.BTN_SHOW_SAMPLE)
        self.FRA_SAMPLE = QtWidgets.QFrame(Dialog)
        self.FRA_SAMPLE.setMinimumSize(QtCore.QSize(0, 192))
        self.FRA_SAMPLE.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.FRA_SAMPLE.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.FRA_SAMPLE.setObjectName("FRA_SAMPLE")
        self.LAY_SAMPLE = QtWidgets.QGridLayout(self.FRA_SAMPLE)
        self.LAY_SAMPLE.setObjectName("LAY_SAMPLE")
        self.verticalLayout_4.addWidget(self.FRA_SAMPLE)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.LBL_TITLE_FILESYSTEM = QtWidgets.QLabel(Dialog)
        self.LBL_TITLE_FILESYSTEM.setObjectName("LBL_TITLE_FILESYSTEM")
        self.verticalLayout.addWidget(self.LBL_TITLE_FILESYSTEM)
        self.BTN_BROWSE = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_BROWSE.sizePolicy().hasHeightForWidth())
        self.BTN_BROWSE.setSizePolicy(sizePolicy)
        self.BTN_BROWSE.setAutoDefault(False)
        self.BTN_BROWSE.setObjectName("BTN_BROWSE")
        self.verticalLayout.addWidget(self.BTN_BROWSE)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LBL_TITLE_MAIN.setText(_translate("Dialog", "Load data"))
        self.LBL_TITLE_MAIN.setProperty("style", _translate("Dialog", "title"))
        self.BTN_REFRESH.setText(_translate("Dialog", "Refresh"))
        self.BTN_HELP.setText(_translate("Dialog", "Help"))
        self.LBL_HAS_DATA_WARNING.setText(_translate("Dialog", "<html><head/><body><p>Data is currently loaded. <a href=\"action:new_model\">Close</a> the current session first, or visit the <a href=\"action:view_workflow\">workflow</a> to manipulate your data.</p></body></html>"))
        self.LBL_HAS_DATA_WARNING.setProperty("style", _translate("Dialog", "warning"))
        self.LBL_TITLE_WORKSPACE.setText(_translate("Dialog", "Workspace"))
        self.LBL_TITLE_WORKSPACE.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_SHOW_WORKSPACE.setText(_translate("Dialog", "Show"))
        self.BTN_SHOW_WORKSPACE.setProperty("style", _translate("Dialog", "dropdown"))
        self.FRA_WORKSPACE.setProperty("style", _translate("Dialog", "contents"))
        self.BTN_NEW_WORKSPACE.setText(_translate("Dialog", "New"))
        self.LBL_TITLE_RECENT.setText(_translate("Dialog", "Recent files"))
        self.LBL_TITLE_RECENT.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_SHOW_RECENT.setText(_translate("Dialog", "Show"))
        self.BTN_SHOW_RECENT.setProperty("style", _translate("Dialog", "dropdown"))
        self.FRA_RECENT.setProperty("style", _translate("Dialog", "contents"))
        self.LBL_TITLE_SAMPLE.setText(_translate("Dialog", "Sample data"))
        self.LBL_TITLE_SAMPLE.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_SHOW_SAMPLE.setText(_translate("Dialog", "Show"))
        self.BTN_SHOW_SAMPLE.setProperty("style", _translate("Dialog", "dropdown"))
        self.FRA_SAMPLE.setProperty("style", _translate("Dialog", "contents"))
        self.LBL_TITLE_FILESYSTEM.setText(_translate("Dialog", "File system"))
        self.LBL_TITLE_FILESYSTEM.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_BROWSE.setText(_translate("Dialog", "Browse..."))


