# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/martinrusilowicz/work/apps/groot/groot_gui/forms/designer/frm_view_options_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1432, 1158)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.PAGE_BROWSER = QtWidgets.QWidget()
        self.PAGE_BROWSER.setObjectName("PAGE_BROWSER")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PAGE_BROWSER)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.PAGE_BROWSER)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.LBL_VISJS_WARNING_2 = QtWidgets.QLabel(self.PAGE_BROWSER)
        self.LBL_VISJS_WARNING_2.setObjectName("LBL_VISJS_WARNING_2")
        self.verticalLayout.addWidget(self.LBL_VISJS_WARNING_2)
        self.RAD_TREE_ASK = QtWidgets.QRadioButton(self.PAGE_BROWSER)
        self.RAD_TREE_ASK.setObjectName("RAD_TREE_ASK")
        self.verticalLayout.addWidget(self.RAD_TREE_ASK)
        self.RAD_TREE_INBUILT = QtWidgets.QRadioButton(self.PAGE_BROWSER)
        self.RAD_TREE_INBUILT.setObjectName("RAD_TREE_INBUILT")
        self.verticalLayout.addWidget(self.RAD_TREE_INBUILT)
        self.RAD_TREE_SYSTEM = QtWidgets.QRadioButton(self.PAGE_BROWSER)
        self.RAD_TREE_SYSTEM.setObjectName("RAD_TREE_SYSTEM")
        self.verticalLayout.addWidget(self.RAD_TREE_SYSTEM)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.stackedWidget.addWidget(self.PAGE_BROWSER)
        self.PAGE_STARTUP = QtWidgets.QWidget()
        self.PAGE_STARTUP.setObjectName("PAGE_STARTUP")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.PAGE_STARTUP)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.PAGE_STARTUP)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.LBL_VISJS_WARNING_3 = QtWidgets.QLabel(self.PAGE_STARTUP)
        self.LBL_VISJS_WARNING_3.setObjectName("LBL_VISJS_WARNING_3")
        self.verticalLayout_2.addWidget(self.LBL_VISJS_WARNING_3)
        self.RAD_STARTUP_MESSAGE = QtWidgets.QRadioButton(self.PAGE_STARTUP)
        self.RAD_STARTUP_MESSAGE.setObjectName("RAD_STARTUP_MESSAGE")
        self.verticalLayout_2.addWidget(self.RAD_STARTUP_MESSAGE)
        self.RAD_STARTUP_WORKFLOW = QtWidgets.QRadioButton(self.PAGE_STARTUP)
        self.RAD_STARTUP_WORKFLOW.setObjectName("RAD_STARTUP_WORKFLOW")
        self.verticalLayout_2.addWidget(self.RAD_STARTUP_WORKFLOW)
        self.RAD_STARTUP_SAMPLES = QtWidgets.QRadioButton(self.PAGE_STARTUP)
        self.RAD_STARTUP_SAMPLES.setObjectName("RAD_STARTUP_SAMPLES")
        self.verticalLayout_2.addWidget(self.RAD_STARTUP_SAMPLES)
        self.RAD_STARTUP_NOTHING = QtWidgets.QRadioButton(self.PAGE_STARTUP)
        self.RAD_STARTUP_NOTHING.setObjectName("RAD_STARTUP_NOTHING")
        self.verticalLayout_2.addWidget(self.RAD_STARTUP_NOTHING)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.PAGE_STARTUP)
        self.PAGE_MDIVIEW = QtWidgets.QWidget()
        self.PAGE_MDIVIEW.setObjectName("PAGE_MDIVIEW")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PAGE_MDIVIEW)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.PAGE_MDIVIEW)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.LBL_VISJS_WARNING_4 = QtWidgets.QLabel(self.PAGE_MDIVIEW)
        self.LBL_VISJS_WARNING_4.setObjectName("LBL_VISJS_WARNING_4")
        self.verticalLayout_3.addWidget(self.LBL_VISJS_WARNING_4)
        self.RAD_WIN_MDI = QtWidgets.QRadioButton(self.PAGE_MDIVIEW)
        self.RAD_WIN_MDI.setObjectName("RAD_WIN_MDI")
        self.verticalLayout_3.addWidget(self.RAD_WIN_MDI)
        self.RAD_WIN_TDI = QtWidgets.QRadioButton(self.PAGE_MDIVIEW)
        self.RAD_WIN_TDI.setObjectName("RAD_WIN_TDI")
        self.verticalLayout_3.addWidget(self.RAD_WIN_TDI)
        self.RAD_WIN_NORMAL = QtWidgets.QRadioButton(self.PAGE_MDIVIEW)
        self.RAD_WIN_NORMAL.setObjectName("RAD_WIN_NORMAL")
        self.verticalLayout_3.addWidget(self.RAD_WIN_NORMAL)
        spacerItem2 = QtWidgets.QSpacerItem(20, 973, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.PAGE_MDIVIEW)
        self.PAGE_JAVASCRIPT = QtWidgets.QWidget()
        self.PAGE_JAVASCRIPT.setObjectName("PAGE_JAVASCRIPT")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.PAGE_JAVASCRIPT)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.PAGE_JAVASCRIPT)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.LBL_VISJS_WARNING_7 = QtWidgets.QLabel(self.PAGE_JAVASCRIPT)
        self.LBL_VISJS_WARNING_7.setObjectName("LBL_VISJS_WARNING_7")
        self.verticalLayout_4.addWidget(self.LBL_VISJS_WARNING_7)
        self.RAD_JS_VIS = QtWidgets.QRadioButton(self.PAGE_JAVASCRIPT)
        self.RAD_JS_VIS.setObjectName("RAD_JS_VIS")
        self.verticalLayout_4.addWidget(self.RAD_JS_VIS)
        self.RAD_JS_CY = QtWidgets.QRadioButton(self.PAGE_JAVASCRIPT)
        self.RAD_JS_CY.setObjectName("RAD_JS_CY")
        self.verticalLayout_4.addWidget(self.RAD_JS_CY)
        self.RAD_JS_NONE = QtWidgets.QRadioButton(self.PAGE_JAVASCRIPT)
        self.RAD_JS_NONE.setObjectName("RAD_JS_NONE")
        self.verticalLayout_4.addWidget(self.RAD_JS_NONE)
        spacerItem3 = QtWidgets.QSpacerItem(20, 989, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.PAGE_JAVASCRIPT)
        self.PAGE_TOOLBAR = QtWidgets.QWidget()
        self.PAGE_TOOLBAR.setObjectName("PAGE_TOOLBAR")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.PAGE_TOOLBAR)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.PAGE_TOOLBAR)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.LBL_VISJS_WARNING_6 = QtWidgets.QLabel(self.PAGE_TOOLBAR)
        self.LBL_VISJS_WARNING_6.setObjectName("LBL_VISJS_WARNING_6")
        self.verticalLayout_5.addWidget(self.LBL_VISJS_WARNING_6)
        self.CHKTOOL_FILE = QtWidgets.QCheckBox(self.PAGE_TOOLBAR)
        self.CHKTOOL_FILE.setObjectName("CHKTOOL_FILE")
        self.verticalLayout_5.addWidget(self.CHKTOOL_FILE)
        self.CHKTOOL_VIS = QtWidgets.QCheckBox(self.PAGE_TOOLBAR)
        self.CHKTOOL_VIS.setObjectName("CHKTOOL_VIS")
        self.verticalLayout_5.addWidget(self.CHKTOOL_VIS)
        self.CHKTOOL_WORKFLOW = QtWidgets.QCheckBox(self.PAGE_TOOLBAR)
        self.CHKTOOL_WORKFLOW.setObjectName("CHKTOOL_WORKFLOW")
        self.verticalLayout_5.addWidget(self.CHKTOOL_WORKFLOW)
        spacerItem4 = QtWidgets.QSpacerItem(20, 1002, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.PAGE_TOOLBAR)
        self.PAGE_MISCELLANEOUS = QtWidgets.QWidget()
        self.PAGE_MISCELLANEOUS.setObjectName("PAGE_MISCELLANEOUS")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.PAGE_MISCELLANEOUS)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.PAGE_MISCELLANEOUS)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.CHK_OPENGL = QtWidgets.QCheckBox(self.PAGE_MISCELLANEOUS)
        self.CHK_OPENGL.setObjectName("CHK_OPENGL")
        self.verticalLayout_6.addWidget(self.CHK_OPENGL)
        self.CHK_SHARE_CONTEXTS = QtWidgets.QCheckBox(self.PAGE_MISCELLANEOUS)
        self.CHK_SHARE_CONTEXTS.setObjectName("CHK_SHARE_CONTEXTS")
        self.verticalLayout_6.addWidget(self.CHK_SHARE_CONTEXTS)
        self.BTN_CLEAR_RECENT = QtWidgets.QPushButton(self.PAGE_MISCELLANEOUS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_CLEAR_RECENT.sizePolicy().hasHeightForWidth())
        self.BTN_CLEAR_RECENT.setSizePolicy(sizePolicy)
        self.BTN_CLEAR_RECENT.setMinimumSize(QtCore.QSize(192, 0))
        self.BTN_CLEAR_RECENT.setMaximumSize(QtCore.QSize(192, 16777215))
        self.BTN_CLEAR_RECENT.setAutoDefault(False)
        self.BTN_CLEAR_RECENT.setObjectName("BTN_CLEAR_RECENT")
        self.verticalLayout_6.addWidget(self.BTN_CLEAR_RECENT)
        self.LBL_VISJS_WARNING_5 = QtWidgets.QLabel(self.PAGE_MISCELLANEOUS)
        self.LBL_VISJS_WARNING_5.setObjectName("LBL_VISJS_WARNING_5")
        self.verticalLayout_6.addWidget(self.LBL_VISJS_WARNING_5)
        self.label_26 = QtWidgets.QLabel(self.PAGE_MISCELLANEOUS)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        self.BTN_INTERMAKE = QtWidgets.QPushButton(self.PAGE_MISCELLANEOUS)
        self.BTN_INTERMAKE.setMinimumSize(QtCore.QSize(192, 0))
        self.BTN_INTERMAKE.setMaximumSize(QtCore.QSize(192, 16777215))
        self.BTN_INTERMAKE.setAutoDefault(False)
        self.BTN_INTERMAKE.setObjectName("BTN_INTERMAKE")
        self.verticalLayout_6.addWidget(self.BTN_INTERMAKE)
        spacerItem5 = QtWidgets.QSpacerItem(20, 897, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.PAGE_MISCELLANEOUS)
        self.PAGE_LEGO_VIEW = QtWidgets.QWidget()
        self.PAGE_LEGO_VIEW.setObjectName("PAGE_LEGO_VIEW")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PAGE_LEGO_VIEW)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 907, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalFrame_2 = QtWidgets.QFrame(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAD_PIANO_YES = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_YES.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_YES.setSizePolicy(sizePolicy)
        self.RAD_PIANO_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_YES.setObjectName("RAD_PIANO_YES")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_YES)
        self.RAD_PIANO_NO = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_NO.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_NO.setSizePolicy(sizePolicy)
        self.RAD_PIANO_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_NO.setObjectName("RAD_PIANO_NO")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_NO)
        self.RAD_PIANO_IND = QtWidgets.QRadioButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_PIANO_IND.sizePolicy().hasHeightForWidth())
        self.RAD_PIANO_IND.setSizePolicy(sizePolicy)
        self.RAD_PIANO_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_PIANO_IND.setObjectName("RAD_PIANO_IND")
        self.horizontalLayout_2.addWidget(self.RAD_PIANO_IND)
        self.gridLayout_3.addWidget(self.horizontalFrame_2, 4, 1, 1, 1)
        self.horizontalFrame_4 = QtWidgets.QFrame(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_4.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_4.setSizePolicy(sizePolicy)
        self.horizontalFrame_4.setObjectName("horizontalFrame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_4)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RAD_POS_YES = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_POS_YES.setSizePolicy(sizePolicy)
        self.RAD_POS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_YES.setObjectName("RAD_POS_YES")
        self.horizontalLayout_5.addWidget(self.RAD_POS_YES)
        self.RAD_POS_NO = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_POS_NO.setSizePolicy(sizePolicy)
        self.RAD_POS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_NO.setObjectName("RAD_POS_NO")
        self.horizontalLayout_5.addWidget(self.RAD_POS_NO)
        self.RAD_POS_IND = QtWidgets.QRadioButton(self.horizontalFrame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_POS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_POS_IND.setSizePolicy(sizePolicy)
        self.RAD_POS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_POS_IND.setObjectName("RAD_POS_IND")
        self.horizontalLayout_5.addWidget(self.RAD_POS_IND)
        self.gridLayout_3.addWidget(self.horizontalFrame_4, 6, 1, 1, 1)
        self.horizontalFrame_9 = QtWidgets.QFrame(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_9.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_9.setSizePolicy(sizePolicy)
        self.horizontalFrame_9.setObjectName("horizontalFrame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalFrame_9)
        self.horizontalLayout_8.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_8.setSpacing(8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.RAD_COMPONENTS_YES = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_YES.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_YES.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_YES.setObjectName("RAD_COMPONENTS_YES")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_YES)
        self.RAD_COMPONENTS_NO = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_NO.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_NO.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_NO.setObjectName("RAD_COMPONENTS_NO")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_NO)
        self.RAD_COMPONENTS_IND = QtWidgets.QRadioButton(self.horizontalFrame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_COMPONENTS_IND.sizePolicy().hasHeightForWidth())
        self.RAD_COMPONENTS_IND.setSizePolicy(sizePolicy)
        self.RAD_COMPONENTS_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_COMPONENTS_IND.setObjectName("RAD_COMPONENTS_IND")
        self.horizontalLayout_8.addWidget(self.RAD_COMPONENTS_IND)
        self.gridLayout_3.addWidget(self.horizontalFrame_9, 8, 1, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.PAGE_LEGO_VIEW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAD_NAME_YES = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_YES.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_YES.setSizePolicy(sizePolicy)
        self.RAD_NAME_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_YES.setObjectName("RAD_NAME_YES")
        self.horizontalLayout.addWidget(self.RAD_NAME_YES)
        self.RAD_NAME_NO = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_NO.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_NO.setSizePolicy(sizePolicy)
        self.RAD_NAME_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_NO.setObjectName("RAD_NAME_NO")
        self.horizontalLayout.addWidget(self.RAD_NAME_NO)
        self.RAD_NAME_IND = QtWidgets.QRadioButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_NAME_IND.sizePolicy().hasHeightForWidth())
        self.RAD_NAME_IND.setSizePolicy(sizePolicy)
        self.RAD_NAME_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_NAME_IND.setObjectName("RAD_NAME_IND")
        self.horizontalLayout.addWidget(self.RAD_NAME_IND)
        self.gridLayout_3.addWidget(self.horizontalFrame, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 3)
        self.label_24 = QtWidgets.QLabel(self.PAGE_LEGO_VIEW)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 0, 1, 3)
        self.stackedWidget.addWidget(self.PAGE_LEGO_VIEW)
        self.PAGE_LEGO_EDIT = QtWidgets.QWidget()
        self.PAGE_LEGO_EDIT.setObjectName("PAGE_LEGO_EDIT")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PAGE_LEGO_EDIT)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalFrame_5 = QtWidgets.QFrame(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_5.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_5.setSizePolicy(sizePolicy)
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_6.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RAD_XSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_YES.setObjectName("RAD_XSNAP_YES")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_YES)
        self.RAD_XSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_NO.setObjectName("RAD_XSNAP_NO")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_NO)
        self.RAD_XSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_XSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_XSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_XSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_XSNAP_IND.setObjectName("RAD_XSNAP_IND")
        self.horizontalLayout_6.addWidget(self.RAD_XSNAP_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_5, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 8, 1, 1, 1)
        self.horizontalFrame_6 = QtWidgets.QFrame(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_6.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_6.setSizePolicy(sizePolicy)
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_7.setSpacing(8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RAD_YSNAP_YES = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_YES.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_YES.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_YES.setObjectName("RAD_YSNAP_YES")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_YES)
        self.RAD_YSNAP_NO = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_NO.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_NO.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_NO.setObjectName("RAD_YSNAP_NO")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_NO)
        self.RAD_YSNAP_IND = QtWidgets.QRadioButton(self.horizontalFrame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_YSNAP_IND.sizePolicy().hasHeightForWidth())
        self.RAD_YSNAP_IND.setSizePolicy(sizePolicy)
        self.RAD_YSNAP_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_YSNAP_IND.setObjectName("RAD_YSNAP_IND")
        self.horizontalLayout_7.addWidget(self.RAD_YSNAP_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_6, 6, 1, 1, 1)
        self.horizontalFrame_3 = QtWidgets.QFrame(self.PAGE_LEGO_EDIT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_3.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_3.setSizePolicy(sizePolicy)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RAD_MOVE_YES = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_YES.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_YES.setSizePolicy(sizePolicy)
        self.RAD_MOVE_YES.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_YES.setObjectName("RAD_MOVE_YES")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_YES)
        self.RAD_MOVE_NO = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_NO.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_NO.setSizePolicy(sizePolicy)
        self.RAD_MOVE_NO.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_NO.setObjectName("RAD_MOVE_NO")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_NO)
        self.RAD_MOVE_IND = QtWidgets.QRadioButton(self.horizontalFrame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RAD_MOVE_IND.sizePolicy().hasHeightForWidth())
        self.RAD_MOVE_IND.setSizePolicy(sizePolicy)
        self.RAD_MOVE_IND.setMinimumSize(QtCore.QSize(150, 0))
        self.RAD_MOVE_IND.setObjectName("RAD_MOVE_IND")
        self.horizontalLayout_4.addWidget(self.RAD_MOVE_IND)
        self.gridLayout_2.addWidget(self.horizontalFrame_3, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.PAGE_LEGO_EDIT)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.PAGE_LEGO_EDIT)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.PAGE_LEGO_EDIT)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.LST_PAGES = QtWidgets.QTreeWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LST_PAGES.sizePolicy().hasHeightForWidth())
        self.LST_PAGES.setSizePolicy(sizePolicy)
        self.LST_PAGES.setRootIsDecorated(False)
        self.LST_PAGES.setItemsExpandable(False)
        self.LST_PAGES.setObjectName("LST_PAGES")
        self.LST_PAGES.headerItem().setText(0, "1")
        self.LST_PAGES.header().setVisible(False)
        self.gridLayout.addWidget(self.LST_PAGES, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PAGE_BROWSER.setProperty("page_title", _translate("Dialog", "Hypertext browser"))
        self.label_11.setText(_translate("Dialog", "Graph browser"))
        self.label_11.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_2.setText(_translate("Dialog", "Choose how to view the graphs.\n"
"Normally Groot will ask you, but you can select a default preference here."))
        self.LBL_VISJS_WARNING_2.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_TREE_ASK.setText(_translate("Dialog", "Ask every time"))
        self.RAD_TREE_INBUILT.setText(_translate("Dialog", "Only use the inbult browser"))
        self.RAD_TREE_SYSTEM.setText(_translate("Dialog", "Only use the system browser"))
        self.PAGE_STARTUP.setProperty("page_title", _translate("Dialog", "Startup"))
        self.label_9.setText(_translate("Dialog", "Startup"))
        self.label_9.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_3.setText(_translate("Dialog", "Choose what to display when Groot starts."))
        self.LBL_VISJS_WARNING_3.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_STARTUP_MESSAGE.setText(_translate("Dialog", "Show the startup message"))
        self.RAD_STARTUP_WORKFLOW.setText(_translate("Dialog", "Show the workflow"))
        self.RAD_STARTUP_SAMPLES.setText(_translate("Dialog", "Show the open file dialogue"))
        self.RAD_STARTUP_NOTHING.setText(_translate("Dialog", "Don\'t show anything"))
        self.PAGE_MDIVIEW.setProperty("page_title", _translate("Dialog", "Document view"))
        self.label_12.setText(_translate("Dialog", "View"))
        self.label_12.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_4.setText(_translate("Dialog", "Select how Groot\'s windows are displayed.\n"
"Note that MDI and TDI may not be supported or work correctly on all platforms.\n"
"Changes to this setting will only take effect when the GUI is restarted."))
        self.LBL_VISJS_WARNING_4.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_WIN_MDI.setToolTip(_translate("Dialog", "Multiple Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_WIN_MDI.setText(_translate("Dialog", "MDI"))
        self.RAD_WIN_TDI.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_WIN_TDI.setText(_translate("Dialog", "TDI"))
        self.RAD_WIN_NORMAL.setToolTip(_translate("Dialog", "Display the windows normally."))
        self.RAD_WIN_NORMAL.setText(_translate("Dialog", "Basic"))
        self.PAGE_JAVASCRIPT.setProperty("page_title", _translate("Dialog", "Javascript"))
        self.label_15.setText(_translate("Dialog", "Javascript"))
        self.label_15.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_7.setText(_translate("Dialog", "Select the default Javascript library used to display graphs.\n"
"If you don\'t select one then Groot\'s static display will be used (not recommended)."))
        self.LBL_VISJS_WARNING_7.setProperty("style", _translate("Dialog", "helpbox"))
        self.RAD_JS_VIS.setToolTip(_translate("Dialog", "Multiple Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_VIS.setText(_translate("Dialog", "Vis.js"))
        self.RAD_JS_CY.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_CY.setText(_translate("Dialog", "Cytoscape.js"))
        self.RAD_JS_NONE.setToolTip(_translate("Dialog", "Tabbed Document Interface.\n"
"Some platforms may not support this mode or may display the windows incorrectly."))
        self.RAD_JS_NONE.setText(_translate("Dialog", "None"))
        self.PAGE_TOOLBAR.setProperty("page_title", _translate("Dialog", "Toolbars"))
        self.label_13.setText(_translate("Dialog", "Toolbar"))
        self.label_13.setProperty("style", _translate("Dialog", "heading"))
        self.LBL_VISJS_WARNING_6.setText(_translate("Dialog", "Select what toolbars are displayed."))
        self.LBL_VISJS_WARNING_6.setProperty("style", _translate("Dialog", "helpbox"))
        self.CHKTOOL_FILE.setText(_translate("Dialog", "File"))
        self.CHKTOOL_VIS.setText(_translate("Dialog", "Visualisers"))
        self.CHKTOOL_WORKFLOW.setText(_translate("Dialog", "Workflow"))
        self.PAGE_MISCELLANEOUS.setProperty("page_title", _translate("Dialog", "Miscellaneous"))
        self.label_4.setText(_translate("Dialog", "Micellaneous"))
        self.label_4.setProperty("style", _translate("Dialog", "heading"))
        self.CHK_OPENGL.setText(_translate("Dialog", "OpenGL"))
        self.CHK_SHARE_CONTEXTS.setText(_translate("Dialog", "Share contexts"))
        self.BTN_CLEAR_RECENT.setText(_translate("Dialog", "Clear recent files history"))
        self.LBL_VISJS_WARNING_5.setText(_translate("Dialog", "Intermake handles algorithm call and response.\n"
"Settings such as whether to keep windows open after running an algorithm can be found here.\n"
"You can also explore the Groot model through Intermake."))
        self.LBL_VISJS_WARNING_5.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_26.setText(_translate("Dialog", "Intermake"))
        self.label_26.setProperty("style", _translate("Dialog", "heading"))
        self.BTN_INTERMAKE.setText(_translate("Dialog", "Intermake configuration"))
        self.PAGE_LEGO_VIEW.setProperty("page_title", _translate("Dialog", "Lego viewing"))
        self.label_5.setText(_translate("Dialog", "Positions"))
        self.label_10.setText(_translate("Dialog", "Components"))
        self.label_2.setText(_translate("Dialog", "Piano rolls"))
        self.label.setText(_translate("Dialog", "Gene names"))
        self.RAD_PIANO_YES.setText(_translate("Dialog", "Always"))
        self.RAD_PIANO_NO.setText(_translate("Dialog", "Never"))
        self.RAD_PIANO_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_POS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_POS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_POS_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_COMPONENTS_YES.setText(_translate("Dialog", "Always"))
        self.RAD_COMPONENTS_NO.setText(_translate("Dialog", "Never"))
        self.RAD_COMPONENTS_IND.setText(_translate("Dialog", "When selected"))
        self.RAD_NAME_YES.setText(_translate("Dialog", "Always"))
        self.RAD_NAME_NO.setText(_translate("Dialog", "Never"))
        self.RAD_NAME_IND.setText(_translate("Dialog", "When selected"))
        self.label_14.setText(_translate("Dialog", "Lego Diagram Viewing"))
        self.label_14.setProperty("style", _translate("Dialog", "heading"))
        self.label_24.setText(_translate("Dialog", "Select what\'s visible on the diagrams."))
        self.label_24.setProperty("style", _translate("Dialog", "helpbox"))
        self.PAGE_LEGO_EDIT.setProperty("page_title", _translate("Dialog", "Lego editing"))
        self.label_3.setText(_translate("Dialog", "Movement"))
        self.RAD_XSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_XSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_XSNAP_IND.setText(_translate("Dialog", "Without ᴄᴛʀʟ"))
        self.label_7.setText(_translate("Dialog", "Y-snap"))
        self.label_6.setText(_translate("Dialog", "X-snap"))
        self.RAD_YSNAP_YES.setText(_translate("Dialog", "Always"))
        self.RAD_YSNAP_NO.setText(_translate("Dialog", "Never"))
        self.RAD_YSNAP_IND.setText(_translate("Dialog", "Without ᴀʟᴛ"))
        self.RAD_MOVE_YES.setText(_translate("Dialog", "Always"))
        self.RAD_MOVE_NO.setText(_translate("Dialog", "Never"))
        self.RAD_MOVE_IND.setText(_translate("Dialog", "Double click toggles"))
        self.label_25.setText(_translate("Dialog", "Select how you\'ll edit your diagrams."))
        self.label_25.setProperty("style", _translate("Dialog", "helpbox"))
        self.label_17.setText(_translate("Dialog", "Lego Diagram Editing"))
        self.label_17.setProperty("style", _translate("Dialog", "heading"))


