#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='pipomatic_hudge_xtracta',
      version='1.2',
      description='Xtracta package',
      author='Hudge',
      author_email='doug@mybusinessautomated.com',
      url='http://www.mybusinessautomated.com',
      py_modules=['pipomatic_hudge_xtracta'],
     )
