# Generated by Django 2.1.3 on 2018-12-03 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_electionevent'),
        ('tracker', '0002_auto_20181126_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('tweet_text', models.CharField(max_length=280)),
                ('tweet_handle', models.CharField(max_length=30)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='election.Candidate')),
            ],
        ),
    ]
