# Generated by Django 2.1.4 on 2018-12-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_electionevent'),
        ('tracker', '0004_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, help_text='If known, name the location where speaker spake.', max_length=250, null=True)),
                ('link', models.URLField(blank=True, help_text='If available, add a link to the quote on social media or as published online.', null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='election.Candidate')),
            ],
        ),
    ]
