# Generated by Django 2.1.4 on 2018-12-18 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_electionevent'),
        ('tracker', '0010_auto_20181217_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('publish_date', models.DateTimeField()),
                ('title', models.CharField(max_length=280)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='election.Candidate')),
            ],
        ),
    ]
