
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-24T21:30:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "abde33cc5791e9fbb5e550ba2ec5126acd49550f",
 "version": "v3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
