
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-01-20T20:57:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d461eeb2f0a5b6e6c1617b075058372f28d367bd",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
